package com.dao.db1.zjsourcedata;

import com.dao.entity.zjsouredata.DwdAsjZfba2SadjxxDd;

import java.util.List;

public interface DwdAsjZfba2SadjxxDdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_asj_zfba2_sadjxx_dd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_asj_zfba2_sadjxx_dd
     *
     * @mbg.generated
     */
    int insert(DwdAsjZfba2SadjxxDd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_asj_zfba2_sadjxx_dd
     *
     * @mbg.generated
     */
    DwdAsjZfba2SadjxxDd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_asj_zfba2_sadjxx_dd
     *
     * @mbg.generated
     */
    List<DwdAsjZfba2SadjxxDd> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_asj_zfba2_sadjxx_dd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DwdAsjZfba2SadjxxDd record);
}