package com.dao.db1.zjsourcedata;

import com.dao.entity.zjsouredata.DwdWpZfba2BaxzhDd;

import java.util.List;

public interface DwdWpZfba2BaxzhDdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_wp_zfba2_baxzh_dd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_wp_zfba2_baxzh_dd
     *
     * @mbg.generated
     */
    int insert(DwdWpZfba2BaxzhDd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_wp_zfba2_baxzh_dd
     *
     * @mbg.generated
     */
    DwdWpZfba2BaxzhDd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_wp_zfba2_baxzh_dd
     *
     * @mbg.generated
     */
    List<DwdWpZfba2BaxzhDd> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_wp_zfba2_baxzh_dd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DwdWpZfba2BaxzhDd record);
}