package com.dao.db1.zjsourcedata;

import com.dao.entity.zjsouredata.LdDwdGjJdcKkgcDs;

import java.util.List;

public interface LdDwdGjJdcKkgcDsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_jdc_kkgc_ds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_jdc_kkgc_ds
     *
     * @mbg.generated
     */
    int insert(LdDwdGjJdcKkgcDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_jdc_kkgc_ds
     *
     * @mbg.generated
     */
    LdDwdGjJdcKkgcDs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_jdc_kkgc_ds
     *
     * @mbg.generated
     */
    List<LdDwdGjJdcKkgcDs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_jdc_kkgc_ds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LdDwdGjJdcKkgcDs record);
}