package com.dao.db1.zjsourcedata;

import com.dao.entity.zjsouredata.LdDwdGjXjTlspXxDs;

import java.util.List;

public interface LdDwdGjXjTlspXxDsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    int insert(LdDwdGjXjTlspXxDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    LdDwdGjXjTlspXxDs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    List<LdDwdGjXjTlspXxDs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LdDwdGjXjTlspXxDs record);
}