package com.dao.db1.zjsourcedata;

import com.dao.entity.zjsouredata.LdDwdGjMacZdtzxxDs;

import java.util.List;

public interface LdDwdGjMacZdtzxxDsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_mac_zdtzxx_ds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_mac_zdtzxx_ds
     *
     * @mbg.generated
     */
    int insert(LdDwdGjMacZdtzxxDs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_mac_zdtzxx_ds
     *
     * @mbg.generated
     */
    LdDwdGjMacZdtzxxDs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_mac_zdtzxx_ds
     *
     * @mbg.generated
     */
    List<LdDwdGjMacZdtzxxDs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_mac_zdtzxx_ds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LdDwdGjMacZdtzxxDs record);
}