package com.dao.db1.zjsourcedata;

import com.dao.entity.zjsouredata.PeopleSrcYlcsry;

import java.util.List;

public interface PeopleSrcYlcsryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_src_ylcsry
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_src_ylcsry
     *
     * @mbg.generated
     */
    int insert(PeopleSrcYlcsry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_src_ylcsry
     *
     * @mbg.generated
     */
    PeopleSrcYlcsry selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_src_ylcsry
     *
     * @mbg.generated
     */
    List<PeopleSrcYlcsry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people_src_ylcsry
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PeopleSrcYlcsry record);
}