package com.dao.entity.zjstat;

import com.dao.entity.sys.ComColumn;

import java.io.Serializable;
import java.util.Date;

public class StatAjxx extends ComColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajbh
     *
     * @mbg.generated
     */
    private String ajbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.jqbh
     *
     * @mbg.generated
     */
    private String jqbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajmc
     *
     * @mbg.generated
     */
    private String ajmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.jyaq
     *
     * @mbg.generated
     */
    private String jyaq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.aybh
     *
     * @mbg.generated
     */
    private String aybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbr_xm
     *
     * @mbg.generated
     */
    private String zbrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbr_sfzh
     *
     * @mbg.generated
     */
    private String zbrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbdw_mc
     *
     * @mbg.generated
     */
    private String zbdwMc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbdw_bh
     *
     * @mbg.generated
     */
    private String zbdwBh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbdw_xtbh
     *
     * @mbg.generated
     */
    private String zbdwXtbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbdw_qydm
     *
     * @mbg.generated
     */
    private String zbdwQydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbdw_qy
     *
     * @mbg.generated
     */
    private String zbdwQy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zbdw_dsdm
     *
     * @mbg.generated
     */
    private String zbdwDsdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.slsj
     *
     * @mbg.generated
     */
    private String slsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.slsj_dt
     *
     * @mbg.generated
     */
    private Date slsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.slsj_int
     *
     * @mbg.generated
     */
    private Integer slsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sarq
     *
     * @mbg.generated
     */
    private String sarq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sarq_dt
     *
     * @mbg.generated
     */
    private Date sarqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sarq_int
     *
     * @mbg.generated
     */
    private Integer sarqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sapzsj
     *
     * @mbg.generated
     */
    private String sapzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sapzsj_dt
     *
     * @mbg.generated
     */
    private Date sapzsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sapzsj_int
     *
     * @mbg.generated
     */
    private Integer sapzsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.larq
     *
     * @mbg.generated
     */
    private String larq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.larq_dt
     *
     * @mbg.generated
     */
    private Date larqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.larq_int
     *
     * @mbg.generated
     */
    private Integer larqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lapzsj
     *
     * @mbg.generated
     */
    private String lapzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lapzsj_dt
     *
     * @mbg.generated
     */
    private Date lapzsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lapzsj_int
     *
     * @mbg.generated
     */
    private Integer lapzsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sfqdkb
     *
     * @mbg.generated
     */
    private String sfqdkb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajlydm
     *
     * @mbg.generated
     */
    private String ajlydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajly
     *
     * @mbg.generated
     */
    private String ajly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sfja
     *
     * @mbg.generated
     */
    private String sfja;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajlxdm
     *
     * @mbg.generated
     */
    private String ajlxdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajlx
     *
     * @mbg.generated
     */
    private String ajlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.shztdm
     *
     * @mbg.generated
     */
    private String shztdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.shzt
     *
     * @mbg.generated
     */
    private String shzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajztdm
     *
     * @mbg.generated
     */
    private String ajztdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajzt
     *
     * @mbg.generated
     */
    private String ajzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.gdqk
     *
     * @mbg.generated
     */
    private String gdqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajmjdm
     *
     * @mbg.generated
     */
    private String ajmjdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajmj
     *
     * @mbg.generated
     */
    private String ajmj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.aymc
     *
     * @mbg.generated
     */
    private String aymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fasjsx
     *
     * @mbg.generated
     */
    private String fasjsx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fasjsx_dt
     *
     * @mbg.generated
     */
    private Date fasjsxDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fasjsx_int
     *
     * @mbg.generated
     */
    private Integer fasjsxInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fadd
     *
     * @mbg.generated
     */
    private String fadd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.jasj
     *
     * @mbg.generated
     */
    private String jasj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.jasj_dt
     *
     * @mbg.generated
     */
    private Date jasjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.jasj_int
     *
     * @mbg.generated
     */
    private Integer jasjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fasjxx
     *
     * @mbg.generated
     */
    private String fasjxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fasjxx_dt
     *
     * @mbg.generated
     */
    private Date fasjxxDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fasjxx_int
     *
     * @mbg.generated
     */
    private Integer fasjxxInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fadd_xzqhdm
     *
     * @mbg.generated
     */
    private String faddXzqhdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.fadd_xzqh
     *
     * @mbg.generated
     */
    private String faddXzqh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lrsj
     *
     * @mbg.generated
     */
    private String lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lrsj_dt
     *
     * @mbg.generated
     */
    private Date lrsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lrsj_int
     *
     * @mbg.generated
     */
    private Integer lrsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.lrr_sfzh
     *
     * @mbg.generated
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.xgr_sfzh
     *
     * @mbg.generated
     */
    private String xgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.xgsj
     *
     * @mbg.generated
     */
    private String xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.xgsj_dt
     *
     * @mbg.generated
     */
    private Date xgsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.xgsj_int
     *
     * @mbg.generated
     */
    private Integer xgsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.isdel
     *
     * @mbg.generated
     */
    private String isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.data_flag
     *
     * @mbg.generated
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.dsdm
     *
     * @mbg.generated
     */
    private String dsdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sfcs
     *
     * @mbg.generated
     */
    private String sfcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.scshsj
     *
     * @mbg.generated
     */
    private String scshsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.scshsj_dt
     *
     * @mbg.generated
     */
    private Date scshsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.scshsj_int
     *
     * @mbg.generated
     */
    private Integer scshsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.scshr_xm
     *
     * @mbg.generated
     */
    private String scshrXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.scshr_sfzh
     *
     * @mbg.generated
     */
    private String scshrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zgqkdm
     *
     * @mbg.generated
     */
    private String zgqkdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.zgqk
     *
     * @mbg.generated
     */
    private String zgqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sjsj
     *
     * @mbg.generated
     */
    private String sjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sjsj_dt
     *
     * @mbg.generated
     */
    private Date sjsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sjsj_int
     *
     * @mbg.generated
     */
    private Integer sjsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.czjgdm
     *
     * @mbg.generated
     */
    private String czjgdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.czjg
     *
     * @mbg.generated
     */
    private String czjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sfxc
     *
     * @mbg.generated
     */
    private String sfxc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sfkjhz
     *
     * @mbg.generated
     */
    private String sfkjhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajbsdm
     *
     * @mbg.generated
     */
    private String ajbsdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.ajbs
     *
     * @mbg.generated
     */
    private String ajbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.xlaymc
     *
     * @mbg.generated
     */
    private String xlaymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.xlaybh
     *
     * @mbg.generated
     */
    private String xlaybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sapzrsfzh
     *
     * @mbg.generated
     */
    private String sapzrsfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sapzrxm
     *
     * @mbg.generated
     */
    private String sapzrxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.bjsj
     *
     * @mbg.generated
     */
    private String bjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.bjsj_dt
     *
     * @mbg.generated
     */
    private Date bjsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.bjsj_int
     *
     * @mbg.generated
     */
    private Integer bjsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.sfyzj
     *
     * @mbg.generated
     */
    private String sfyzj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.op_type
     *
     * @mbg.generated
     */
    private String opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.time_stamp
     *
     * @mbg.generated
     */
    private String timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.dwd_yxbz
     *
     * @mbg.generated
     */
    private String dwdYxbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.dwd_zjid
     *
     * @mbg.generated
     */
    private String dwdZjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.dwd_loadtime
     *
     * @mbg.generated
     */
    private String dwdLoadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.dwd_upDateTime
     *
     * @mbg.generated
     */
    private String dwdUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.dep_code
     *
     * @mbg.generated
     */
    private String depCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.source_code
     *
     * @mbg.generated
     */
    private String sourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.source_code_single
     *
     * @mbg.generated
     */
    private String sourceCodeSingle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.source_kind
     *
     * @mbg.generated
     */
    private String sourceKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.source_kind1
     *
     * @mbg.generated
     */
    private String sourceKind1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_ajxx.source_kind2
     *
     * @mbg.generated
     */
    private String sourceKind2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stat_ajxx
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.id
     *
     * @return the value of stat_ajxx.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.id
     *
     * @param id the value for stat_ajxx.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajbh
     *
     * @return the value of stat_ajxx.ajbh
     *
     * @mbg.generated
     */
    public String getAjbh() {
        return ajbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajbh
     *
     * @param ajbh the value for stat_ajxx.ajbh
     *
     * @mbg.generated
     */
    public void setAjbh(String ajbh) {
        this.ajbh = ajbh == null ? null : ajbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.jqbh
     *
     * @return the value of stat_ajxx.jqbh
     *
     * @mbg.generated
     */
    public String getJqbh() {
        return jqbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.jqbh
     *
     * @param jqbh the value for stat_ajxx.jqbh
     *
     * @mbg.generated
     */
    public void setJqbh(String jqbh) {
        this.jqbh = jqbh == null ? null : jqbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajmc
     *
     * @return the value of stat_ajxx.ajmc
     *
     * @mbg.generated
     */
    public String getAjmc() {
        return ajmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajmc
     *
     * @param ajmc the value for stat_ajxx.ajmc
     *
     * @mbg.generated
     */
    public void setAjmc(String ajmc) {
        this.ajmc = ajmc == null ? null : ajmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.jyaq
     *
     * @return the value of stat_ajxx.jyaq
     *
     * @mbg.generated
     */
    public String getJyaq() {
        return jyaq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.jyaq
     *
     * @param jyaq the value for stat_ajxx.jyaq
     *
     * @mbg.generated
     */
    public void setJyaq(String jyaq) {
        this.jyaq = jyaq == null ? null : jyaq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.aybh
     *
     * @return the value of stat_ajxx.aybh
     *
     * @mbg.generated
     */
    public String getAybh() {
        return aybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.aybh
     *
     * @param aybh the value for stat_ajxx.aybh
     *
     * @mbg.generated
     */
    public void setAybh(String aybh) {
        this.aybh = aybh == null ? null : aybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbr_xm
     *
     * @return the value of stat_ajxx.zbr_xm
     *
     * @mbg.generated
     */
    public String getZbrXm() {
        return zbrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbr_xm
     *
     * @param zbrXm the value for stat_ajxx.zbr_xm
     *
     * @mbg.generated
     */
    public void setZbrXm(String zbrXm) {
        this.zbrXm = zbrXm == null ? null : zbrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbr_sfzh
     *
     * @return the value of stat_ajxx.zbr_sfzh
     *
     * @mbg.generated
     */
    public String getZbrSfzh() {
        return zbrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbr_sfzh
     *
     * @param zbrSfzh the value for stat_ajxx.zbr_sfzh
     *
     * @mbg.generated
     */
    public void setZbrSfzh(String zbrSfzh) {
        this.zbrSfzh = zbrSfzh == null ? null : zbrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbdw_mc
     *
     * @return the value of stat_ajxx.zbdw_mc
     *
     * @mbg.generated
     */
    public String getZbdwMc() {
        return zbdwMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbdw_mc
     *
     * @param zbdwMc the value for stat_ajxx.zbdw_mc
     *
     * @mbg.generated
     */
    public void setZbdwMc(String zbdwMc) {
        this.zbdwMc = zbdwMc == null ? null : zbdwMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbdw_bh
     *
     * @return the value of stat_ajxx.zbdw_bh
     *
     * @mbg.generated
     */
    public String getZbdwBh() {
        return zbdwBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbdw_bh
     *
     * @param zbdwBh the value for stat_ajxx.zbdw_bh
     *
     * @mbg.generated
     */
    public void setZbdwBh(String zbdwBh) {
        this.zbdwBh = zbdwBh == null ? null : zbdwBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbdw_xtbh
     *
     * @return the value of stat_ajxx.zbdw_xtbh
     *
     * @mbg.generated
     */
    public String getZbdwXtbh() {
        return zbdwXtbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbdw_xtbh
     *
     * @param zbdwXtbh the value for stat_ajxx.zbdw_xtbh
     *
     * @mbg.generated
     */
    public void setZbdwXtbh(String zbdwXtbh) {
        this.zbdwXtbh = zbdwXtbh == null ? null : zbdwXtbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbdw_qydm
     *
     * @return the value of stat_ajxx.zbdw_qydm
     *
     * @mbg.generated
     */
    public String getZbdwQydm() {
        return zbdwQydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbdw_qydm
     *
     * @param zbdwQydm the value for stat_ajxx.zbdw_qydm
     *
     * @mbg.generated
     */
    public void setZbdwQydm(String zbdwQydm) {
        this.zbdwQydm = zbdwQydm == null ? null : zbdwQydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbdw_qy
     *
     * @return the value of stat_ajxx.zbdw_qy
     *
     * @mbg.generated
     */
    public String getZbdwQy() {
        return zbdwQy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbdw_qy
     *
     * @param zbdwQy the value for stat_ajxx.zbdw_qy
     *
     * @mbg.generated
     */
    public void setZbdwQy(String zbdwQy) {
        this.zbdwQy = zbdwQy == null ? null : zbdwQy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zbdw_dsdm
     *
     * @return the value of stat_ajxx.zbdw_dsdm
     *
     * @mbg.generated
     */
    public String getZbdwDsdm() {
        return zbdwDsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zbdw_dsdm
     *
     * @param zbdwDsdm the value for stat_ajxx.zbdw_dsdm
     *
     * @mbg.generated
     */
    public void setZbdwDsdm(String zbdwDsdm) {
        this.zbdwDsdm = zbdwDsdm == null ? null : zbdwDsdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.slsj
     *
     * @return the value of stat_ajxx.slsj
     *
     * @mbg.generated
     */
    public String getSlsj() {
        return slsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.slsj
     *
     * @param slsj the value for stat_ajxx.slsj
     *
     * @mbg.generated
     */
    public void setSlsj(String slsj) {
        this.slsj = slsj == null ? null : slsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.slsj_dt
     *
     * @return the value of stat_ajxx.slsj_dt
     *
     * @mbg.generated
     */
    public Date getSlsjDt() {
        return slsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.slsj_dt
     *
     * @param slsjDt the value for stat_ajxx.slsj_dt
     *
     * @mbg.generated
     */
    public void setSlsjDt(Date slsjDt) {
        this.slsjDt = slsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.slsj_int
     *
     * @return the value of stat_ajxx.slsj_int
     *
     * @mbg.generated
     */
    public Integer getSlsjInt() {
        return slsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.slsj_int
     *
     * @param slsjInt the value for stat_ajxx.slsj_int
     *
     * @mbg.generated
     */
    public void setSlsjInt(Integer slsjInt) {
        this.slsjInt = slsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sarq
     *
     * @return the value of stat_ajxx.sarq
     *
     * @mbg.generated
     */
    public String getSarq() {
        return sarq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sarq
     *
     * @param sarq the value for stat_ajxx.sarq
     *
     * @mbg.generated
     */
    public void setSarq(String sarq) {
        this.sarq = sarq == null ? null : sarq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sarq_dt
     *
     * @return the value of stat_ajxx.sarq_dt
     *
     * @mbg.generated
     */
    public Date getSarqDt() {
        return sarqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sarq_dt
     *
     * @param sarqDt the value for stat_ajxx.sarq_dt
     *
     * @mbg.generated
     */
    public void setSarqDt(Date sarqDt) {
        this.sarqDt = sarqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sarq_int
     *
     * @return the value of stat_ajxx.sarq_int
     *
     * @mbg.generated
     */
    public Integer getSarqInt() {
        return sarqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sarq_int
     *
     * @param sarqInt the value for stat_ajxx.sarq_int
     *
     * @mbg.generated
     */
    public void setSarqInt(Integer sarqInt) {
        this.sarqInt = sarqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sapzsj
     *
     * @return the value of stat_ajxx.sapzsj
     *
     * @mbg.generated
     */
    public String getSapzsj() {
        return sapzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sapzsj
     *
     * @param sapzsj the value for stat_ajxx.sapzsj
     *
     * @mbg.generated
     */
    public void setSapzsj(String sapzsj) {
        this.sapzsj = sapzsj == null ? null : sapzsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sapzsj_dt
     *
     * @return the value of stat_ajxx.sapzsj_dt
     *
     * @mbg.generated
     */
    public Date getSapzsjDt() {
        return sapzsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sapzsj_dt
     *
     * @param sapzsjDt the value for stat_ajxx.sapzsj_dt
     *
     * @mbg.generated
     */
    public void setSapzsjDt(Date sapzsjDt) {
        this.sapzsjDt = sapzsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sapzsj_int
     *
     * @return the value of stat_ajxx.sapzsj_int
     *
     * @mbg.generated
     */
    public Integer getSapzsjInt() {
        return sapzsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sapzsj_int
     *
     * @param sapzsjInt the value for stat_ajxx.sapzsj_int
     *
     * @mbg.generated
     */
    public void setSapzsjInt(Integer sapzsjInt) {
        this.sapzsjInt = sapzsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.larq
     *
     * @return the value of stat_ajxx.larq
     *
     * @mbg.generated
     */
    public String getLarq() {
        return larq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.larq
     *
     * @param larq the value for stat_ajxx.larq
     *
     * @mbg.generated
     */
    public void setLarq(String larq) {
        this.larq = larq == null ? null : larq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.larq_dt
     *
     * @return the value of stat_ajxx.larq_dt
     *
     * @mbg.generated
     */
    public Date getLarqDt() {
        return larqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.larq_dt
     *
     * @param larqDt the value for stat_ajxx.larq_dt
     *
     * @mbg.generated
     */
    public void setLarqDt(Date larqDt) {
        this.larqDt = larqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.larq_int
     *
     * @return the value of stat_ajxx.larq_int
     *
     * @mbg.generated
     */
    public Integer getLarqInt() {
        return larqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.larq_int
     *
     * @param larqInt the value for stat_ajxx.larq_int
     *
     * @mbg.generated
     */
    public void setLarqInt(Integer larqInt) {
        this.larqInt = larqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lapzsj
     *
     * @return the value of stat_ajxx.lapzsj
     *
     * @mbg.generated
     */
    public String getLapzsj() {
        return lapzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lapzsj
     *
     * @param lapzsj the value for stat_ajxx.lapzsj
     *
     * @mbg.generated
     */
    public void setLapzsj(String lapzsj) {
        this.lapzsj = lapzsj == null ? null : lapzsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lapzsj_dt
     *
     * @return the value of stat_ajxx.lapzsj_dt
     *
     * @mbg.generated
     */
    public Date getLapzsjDt() {
        return lapzsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lapzsj_dt
     *
     * @param lapzsjDt the value for stat_ajxx.lapzsj_dt
     *
     * @mbg.generated
     */
    public void setLapzsjDt(Date lapzsjDt) {
        this.lapzsjDt = lapzsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lapzsj_int
     *
     * @return the value of stat_ajxx.lapzsj_int
     *
     * @mbg.generated
     */
    public Integer getLapzsjInt() {
        return lapzsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lapzsj_int
     *
     * @param lapzsjInt the value for stat_ajxx.lapzsj_int
     *
     * @mbg.generated
     */
    public void setLapzsjInt(Integer lapzsjInt) {
        this.lapzsjInt = lapzsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sfqdkb
     *
     * @return the value of stat_ajxx.sfqdkb
     *
     * @mbg.generated
     */
    public String getSfqdkb() {
        return sfqdkb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sfqdkb
     *
     * @param sfqdkb the value for stat_ajxx.sfqdkb
     *
     * @mbg.generated
     */
    public void setSfqdkb(String sfqdkb) {
        this.sfqdkb = sfqdkb == null ? null : sfqdkb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajlydm
     *
     * @return the value of stat_ajxx.ajlydm
     *
     * @mbg.generated
     */
    public String getAjlydm() {
        return ajlydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajlydm
     *
     * @param ajlydm the value for stat_ajxx.ajlydm
     *
     * @mbg.generated
     */
    public void setAjlydm(String ajlydm) {
        this.ajlydm = ajlydm == null ? null : ajlydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajly
     *
     * @return the value of stat_ajxx.ajly
     *
     * @mbg.generated
     */
    public String getAjly() {
        return ajly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajly
     *
     * @param ajly the value for stat_ajxx.ajly
     *
     * @mbg.generated
     */
    public void setAjly(String ajly) {
        this.ajly = ajly == null ? null : ajly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sfja
     *
     * @return the value of stat_ajxx.sfja
     *
     * @mbg.generated
     */
    public String getSfja() {
        return sfja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sfja
     *
     * @param sfja the value for stat_ajxx.sfja
     *
     * @mbg.generated
     */
    public void setSfja(String sfja) {
        this.sfja = sfja == null ? null : sfja.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajlxdm
     *
     * @return the value of stat_ajxx.ajlxdm
     *
     * @mbg.generated
     */
    public String getAjlxdm() {
        return ajlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajlxdm
     *
     * @param ajlxdm the value for stat_ajxx.ajlxdm
     *
     * @mbg.generated
     */
    public void setAjlxdm(String ajlxdm) {
        this.ajlxdm = ajlxdm == null ? null : ajlxdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajlx
     *
     * @return the value of stat_ajxx.ajlx
     *
     * @mbg.generated
     */
    public String getAjlx() {
        return ajlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajlx
     *
     * @param ajlx the value for stat_ajxx.ajlx
     *
     * @mbg.generated
     */
    public void setAjlx(String ajlx) {
        this.ajlx = ajlx == null ? null : ajlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.shztdm
     *
     * @return the value of stat_ajxx.shztdm
     *
     * @mbg.generated
     */
    public String getShztdm() {
        return shztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.shztdm
     *
     * @param shztdm the value for stat_ajxx.shztdm
     *
     * @mbg.generated
     */
    public void setShztdm(String shztdm) {
        this.shztdm = shztdm == null ? null : shztdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.shzt
     *
     * @return the value of stat_ajxx.shzt
     *
     * @mbg.generated
     */
    public String getShzt() {
        return shzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.shzt
     *
     * @param shzt the value for stat_ajxx.shzt
     *
     * @mbg.generated
     */
    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajztdm
     *
     * @return the value of stat_ajxx.ajztdm
     *
     * @mbg.generated
     */
    public String getAjztdm() {
        return ajztdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajztdm
     *
     * @param ajztdm the value for stat_ajxx.ajztdm
     *
     * @mbg.generated
     */
    public void setAjztdm(String ajztdm) {
        this.ajztdm = ajztdm == null ? null : ajztdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajzt
     *
     * @return the value of stat_ajxx.ajzt
     *
     * @mbg.generated
     */
    public String getAjzt() {
        return ajzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajzt
     *
     * @param ajzt the value for stat_ajxx.ajzt
     *
     * @mbg.generated
     */
    public void setAjzt(String ajzt) {
        this.ajzt = ajzt == null ? null : ajzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.gdqk
     *
     * @return the value of stat_ajxx.gdqk
     *
     * @mbg.generated
     */
    public String getGdqk() {
        return gdqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.gdqk
     *
     * @param gdqk the value for stat_ajxx.gdqk
     *
     * @mbg.generated
     */
    public void setGdqk(String gdqk) {
        this.gdqk = gdqk == null ? null : gdqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajmjdm
     *
     * @return the value of stat_ajxx.ajmjdm
     *
     * @mbg.generated
     */
    public String getAjmjdm() {
        return ajmjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajmjdm
     *
     * @param ajmjdm the value for stat_ajxx.ajmjdm
     *
     * @mbg.generated
     */
    public void setAjmjdm(String ajmjdm) {
        this.ajmjdm = ajmjdm == null ? null : ajmjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajmj
     *
     * @return the value of stat_ajxx.ajmj
     *
     * @mbg.generated
     */
    public String getAjmj() {
        return ajmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajmj
     *
     * @param ajmj the value for stat_ajxx.ajmj
     *
     * @mbg.generated
     */
    public void setAjmj(String ajmj) {
        this.ajmj = ajmj == null ? null : ajmj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.aymc
     *
     * @return the value of stat_ajxx.aymc
     *
     * @mbg.generated
     */
    public String getAymc() {
        return aymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.aymc
     *
     * @param aymc the value for stat_ajxx.aymc
     *
     * @mbg.generated
     */
    public void setAymc(String aymc) {
        this.aymc = aymc == null ? null : aymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fasjsx
     *
     * @return the value of stat_ajxx.fasjsx
     *
     * @mbg.generated
     */
    public String getFasjsx() {
        return fasjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fasjsx
     *
     * @param fasjsx the value for stat_ajxx.fasjsx
     *
     * @mbg.generated
     */
    public void setFasjsx(String fasjsx) {
        this.fasjsx = fasjsx == null ? null : fasjsx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fasjsx_dt
     *
     * @return the value of stat_ajxx.fasjsx_dt
     *
     * @mbg.generated
     */
    public Date getFasjsxDt() {
        return fasjsxDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fasjsx_dt
     *
     * @param fasjsxDt the value for stat_ajxx.fasjsx_dt
     *
     * @mbg.generated
     */
    public void setFasjsxDt(Date fasjsxDt) {
        this.fasjsxDt = fasjsxDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fasjsx_int
     *
     * @return the value of stat_ajxx.fasjsx_int
     *
     * @mbg.generated
     */
    public Integer getFasjsxInt() {
        return fasjsxInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fasjsx_int
     *
     * @param fasjsxInt the value for stat_ajxx.fasjsx_int
     *
     * @mbg.generated
     */
    public void setFasjsxInt(Integer fasjsxInt) {
        this.fasjsxInt = fasjsxInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fadd
     *
     * @return the value of stat_ajxx.fadd
     *
     * @mbg.generated
     */
    public String getFadd() {
        return fadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fadd
     *
     * @param fadd the value for stat_ajxx.fadd
     *
     * @mbg.generated
     */
    public void setFadd(String fadd) {
        this.fadd = fadd == null ? null : fadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.jasj
     *
     * @return the value of stat_ajxx.jasj
     *
     * @mbg.generated
     */
    public String getJasj() {
        return jasj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.jasj
     *
     * @param jasj the value for stat_ajxx.jasj
     *
     * @mbg.generated
     */
    public void setJasj(String jasj) {
        this.jasj = jasj == null ? null : jasj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.jasj_dt
     *
     * @return the value of stat_ajxx.jasj_dt
     *
     * @mbg.generated
     */
    public Date getJasjDt() {
        return jasjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.jasj_dt
     *
     * @param jasjDt the value for stat_ajxx.jasj_dt
     *
     * @mbg.generated
     */
    public void setJasjDt(Date jasjDt) {
        this.jasjDt = jasjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.jasj_int
     *
     * @return the value of stat_ajxx.jasj_int
     *
     * @mbg.generated
     */
    public Integer getJasjInt() {
        return jasjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.jasj_int
     *
     * @param jasjInt the value for stat_ajxx.jasj_int
     *
     * @mbg.generated
     */
    public void setJasjInt(Integer jasjInt) {
        this.jasjInt = jasjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fasjxx
     *
     * @return the value of stat_ajxx.fasjxx
     *
     * @mbg.generated
     */
    public String getFasjxx() {
        return fasjxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fasjxx
     *
     * @param fasjxx the value for stat_ajxx.fasjxx
     *
     * @mbg.generated
     */
    public void setFasjxx(String fasjxx) {
        this.fasjxx = fasjxx == null ? null : fasjxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fasjxx_dt
     *
     * @return the value of stat_ajxx.fasjxx_dt
     *
     * @mbg.generated
     */
    public Date getFasjxxDt() {
        return fasjxxDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fasjxx_dt
     *
     * @param fasjxxDt the value for stat_ajxx.fasjxx_dt
     *
     * @mbg.generated
     */
    public void setFasjxxDt(Date fasjxxDt) {
        this.fasjxxDt = fasjxxDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fasjxx_int
     *
     * @return the value of stat_ajxx.fasjxx_int
     *
     * @mbg.generated
     */
    public Integer getFasjxxInt() {
        return fasjxxInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fasjxx_int
     *
     * @param fasjxxInt the value for stat_ajxx.fasjxx_int
     *
     * @mbg.generated
     */
    public void setFasjxxInt(Integer fasjxxInt) {
        this.fasjxxInt = fasjxxInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fadd_xzqhdm
     *
     * @return the value of stat_ajxx.fadd_xzqhdm
     *
     * @mbg.generated
     */
    public String getFaddXzqhdm() {
        return faddXzqhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fadd_xzqhdm
     *
     * @param faddXzqhdm the value for stat_ajxx.fadd_xzqhdm
     *
     * @mbg.generated
     */
    public void setFaddXzqhdm(String faddXzqhdm) {
        this.faddXzqhdm = faddXzqhdm == null ? null : faddXzqhdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.fadd_xzqh
     *
     * @return the value of stat_ajxx.fadd_xzqh
     *
     * @mbg.generated
     */
    public String getFaddXzqh() {
        return faddXzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.fadd_xzqh
     *
     * @param faddXzqh the value for stat_ajxx.fadd_xzqh
     *
     * @mbg.generated
     */
    public void setFaddXzqh(String faddXzqh) {
        this.faddXzqh = faddXzqh == null ? null : faddXzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lrsj
     *
     * @return the value of stat_ajxx.lrsj
     *
     * @mbg.generated
     */
    public String getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lrsj
     *
     * @param lrsj the value for stat_ajxx.lrsj
     *
     * @mbg.generated
     */
    public void setLrsj(String lrsj) {
        this.lrsj = lrsj == null ? null : lrsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lrsj_dt
     *
     * @return the value of stat_ajxx.lrsj_dt
     *
     * @mbg.generated
     */
    public Date getLrsjDt() {
        return lrsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lrsj_dt
     *
     * @param lrsjDt the value for stat_ajxx.lrsj_dt
     *
     * @mbg.generated
     */
    public void setLrsjDt(Date lrsjDt) {
        this.lrsjDt = lrsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lrsj_int
     *
     * @return the value of stat_ajxx.lrsj_int
     *
     * @mbg.generated
     */
    public Integer getLrsjInt() {
        return lrsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lrsj_int
     *
     * @param lrsjInt the value for stat_ajxx.lrsj_int
     *
     * @mbg.generated
     */
    public void setLrsjInt(Integer lrsjInt) {
        this.lrsjInt = lrsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.lrr_sfzh
     *
     * @return the value of stat_ajxx.lrr_sfzh
     *
     * @mbg.generated
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.lrr_sfzh
     *
     * @param lrrSfzh the value for stat_ajxx.lrr_sfzh
     *
     * @mbg.generated
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.xgr_sfzh
     *
     * @return the value of stat_ajxx.xgr_sfzh
     *
     * @mbg.generated
     */
    public String getXgrSfzh() {
        return xgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.xgr_sfzh
     *
     * @param xgrSfzh the value for stat_ajxx.xgr_sfzh
     *
     * @mbg.generated
     */
    public void setXgrSfzh(String xgrSfzh) {
        this.xgrSfzh = xgrSfzh == null ? null : xgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.xgsj
     *
     * @return the value of stat_ajxx.xgsj
     *
     * @mbg.generated
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.xgsj
     *
     * @param xgsj the value for stat_ajxx.xgsj
     *
     * @mbg.generated
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.xgsj_dt
     *
     * @return the value of stat_ajxx.xgsj_dt
     *
     * @mbg.generated
     */
    public Date getXgsjDt() {
        return xgsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.xgsj_dt
     *
     * @param xgsjDt the value for stat_ajxx.xgsj_dt
     *
     * @mbg.generated
     */
    public void setXgsjDt(Date xgsjDt) {
        this.xgsjDt = xgsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.xgsj_int
     *
     * @return the value of stat_ajxx.xgsj_int
     *
     * @mbg.generated
     */
    public Integer getXgsjInt() {
        return xgsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.xgsj_int
     *
     * @param xgsjInt the value for stat_ajxx.xgsj_int
     *
     * @mbg.generated
     */
    public void setXgsjInt(Integer xgsjInt) {
        this.xgsjInt = xgsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.isdel
     *
     * @return the value of stat_ajxx.isdel
     *
     * @mbg.generated
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.isdel
     *
     * @param isdel the value for stat_ajxx.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel == null ? null : isdel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.data_flag
     *
     * @return the value of stat_ajxx.data_flag
     *
     * @mbg.generated
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.data_flag
     *
     * @param dataFlag the value for stat_ajxx.data_flag
     *
     * @mbg.generated
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.dsdm
     *
     * @return the value of stat_ajxx.dsdm
     *
     * @mbg.generated
     */
    public String getDsdm() {
        return dsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.dsdm
     *
     * @param dsdm the value for stat_ajxx.dsdm
     *
     * @mbg.generated
     */
    public void setDsdm(String dsdm) {
        this.dsdm = dsdm == null ? null : dsdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sfcs
     *
     * @return the value of stat_ajxx.sfcs
     *
     * @mbg.generated
     */
    public String getSfcs() {
        return sfcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sfcs
     *
     * @param sfcs the value for stat_ajxx.sfcs
     *
     * @mbg.generated
     */
    public void setSfcs(String sfcs) {
        this.sfcs = sfcs == null ? null : sfcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.scshsj
     *
     * @return the value of stat_ajxx.scshsj
     *
     * @mbg.generated
     */
    public String getScshsj() {
        return scshsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.scshsj
     *
     * @param scshsj the value for stat_ajxx.scshsj
     *
     * @mbg.generated
     */
    public void setScshsj(String scshsj) {
        this.scshsj = scshsj == null ? null : scshsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.scshsj_dt
     *
     * @return the value of stat_ajxx.scshsj_dt
     *
     * @mbg.generated
     */
    public Date getScshsjDt() {
        return scshsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.scshsj_dt
     *
     * @param scshsjDt the value for stat_ajxx.scshsj_dt
     *
     * @mbg.generated
     */
    public void setScshsjDt(Date scshsjDt) {
        this.scshsjDt = scshsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.scshsj_int
     *
     * @return the value of stat_ajxx.scshsj_int
     *
     * @mbg.generated
     */
    public Integer getScshsjInt() {
        return scshsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.scshsj_int
     *
     * @param scshsjInt the value for stat_ajxx.scshsj_int
     *
     * @mbg.generated
     */
    public void setScshsjInt(Integer scshsjInt) {
        this.scshsjInt = scshsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.scshr_xm
     *
     * @return the value of stat_ajxx.scshr_xm
     *
     * @mbg.generated
     */
    public String getScshrXm() {
        return scshrXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.scshr_xm
     *
     * @param scshrXm the value for stat_ajxx.scshr_xm
     *
     * @mbg.generated
     */
    public void setScshrXm(String scshrXm) {
        this.scshrXm = scshrXm == null ? null : scshrXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.scshr_sfzh
     *
     * @return the value of stat_ajxx.scshr_sfzh
     *
     * @mbg.generated
     */
    public String getScshrSfzh() {
        return scshrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.scshr_sfzh
     *
     * @param scshrSfzh the value for stat_ajxx.scshr_sfzh
     *
     * @mbg.generated
     */
    public void setScshrSfzh(String scshrSfzh) {
        this.scshrSfzh = scshrSfzh == null ? null : scshrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zgqkdm
     *
     * @return the value of stat_ajxx.zgqkdm
     *
     * @mbg.generated
     */
    public String getZgqkdm() {
        return zgqkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zgqkdm
     *
     * @param zgqkdm the value for stat_ajxx.zgqkdm
     *
     * @mbg.generated
     */
    public void setZgqkdm(String zgqkdm) {
        this.zgqkdm = zgqkdm == null ? null : zgqkdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.zgqk
     *
     * @return the value of stat_ajxx.zgqk
     *
     * @mbg.generated
     */
    public String getZgqk() {
        return zgqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.zgqk
     *
     * @param zgqk the value for stat_ajxx.zgqk
     *
     * @mbg.generated
     */
    public void setZgqk(String zgqk) {
        this.zgqk = zgqk == null ? null : zgqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sjsj
     *
     * @return the value of stat_ajxx.sjsj
     *
     * @mbg.generated
     */
    public String getSjsj() {
        return sjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sjsj
     *
     * @param sjsj the value for stat_ajxx.sjsj
     *
     * @mbg.generated
     */
    public void setSjsj(String sjsj) {
        this.sjsj = sjsj == null ? null : sjsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sjsj_dt
     *
     * @return the value of stat_ajxx.sjsj_dt
     *
     * @mbg.generated
     */
    public Date getSjsjDt() {
        return sjsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sjsj_dt
     *
     * @param sjsjDt the value for stat_ajxx.sjsj_dt
     *
     * @mbg.generated
     */
    public void setSjsjDt(Date sjsjDt) {
        this.sjsjDt = sjsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sjsj_int
     *
     * @return the value of stat_ajxx.sjsj_int
     *
     * @mbg.generated
     */
    public Integer getSjsjInt() {
        return sjsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sjsj_int
     *
     * @param sjsjInt the value for stat_ajxx.sjsj_int
     *
     * @mbg.generated
     */
    public void setSjsjInt(Integer sjsjInt) {
        this.sjsjInt = sjsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.czjgdm
     *
     * @return the value of stat_ajxx.czjgdm
     *
     * @mbg.generated
     */
    public String getCzjgdm() {
        return czjgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.czjgdm
     *
     * @param czjgdm the value for stat_ajxx.czjgdm
     *
     * @mbg.generated
     */
    public void setCzjgdm(String czjgdm) {
        this.czjgdm = czjgdm == null ? null : czjgdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.czjg
     *
     * @return the value of stat_ajxx.czjg
     *
     * @mbg.generated
     */
    public String getCzjg() {
        return czjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.czjg
     *
     * @param czjg the value for stat_ajxx.czjg
     *
     * @mbg.generated
     */
    public void setCzjg(String czjg) {
        this.czjg = czjg == null ? null : czjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sfxc
     *
     * @return the value of stat_ajxx.sfxc
     *
     * @mbg.generated
     */
    public String getSfxc() {
        return sfxc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sfxc
     *
     * @param sfxc the value for stat_ajxx.sfxc
     *
     * @mbg.generated
     */
    public void setSfxc(String sfxc) {
        this.sfxc = sfxc == null ? null : sfxc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sfkjhz
     *
     * @return the value of stat_ajxx.sfkjhz
     *
     * @mbg.generated
     */
    public String getSfkjhz() {
        return sfkjhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sfkjhz
     *
     * @param sfkjhz the value for stat_ajxx.sfkjhz
     *
     * @mbg.generated
     */
    public void setSfkjhz(String sfkjhz) {
        this.sfkjhz = sfkjhz == null ? null : sfkjhz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajbsdm
     *
     * @return the value of stat_ajxx.ajbsdm
     *
     * @mbg.generated
     */
    public String getAjbsdm() {
        return ajbsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajbsdm
     *
     * @param ajbsdm the value for stat_ajxx.ajbsdm
     *
     * @mbg.generated
     */
    public void setAjbsdm(String ajbsdm) {
        this.ajbsdm = ajbsdm == null ? null : ajbsdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.ajbs
     *
     * @return the value of stat_ajxx.ajbs
     *
     * @mbg.generated
     */
    public String getAjbs() {
        return ajbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.ajbs
     *
     * @param ajbs the value for stat_ajxx.ajbs
     *
     * @mbg.generated
     */
    public void setAjbs(String ajbs) {
        this.ajbs = ajbs == null ? null : ajbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.xlaymc
     *
     * @return the value of stat_ajxx.xlaymc
     *
     * @mbg.generated
     */
    public String getXlaymc() {
        return xlaymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.xlaymc
     *
     * @param xlaymc the value for stat_ajxx.xlaymc
     *
     * @mbg.generated
     */
    public void setXlaymc(String xlaymc) {
        this.xlaymc = xlaymc == null ? null : xlaymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.xlaybh
     *
     * @return the value of stat_ajxx.xlaybh
     *
     * @mbg.generated
     */
    public String getXlaybh() {
        return xlaybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.xlaybh
     *
     * @param xlaybh the value for stat_ajxx.xlaybh
     *
     * @mbg.generated
     */
    public void setXlaybh(String xlaybh) {
        this.xlaybh = xlaybh == null ? null : xlaybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sapzrsfzh
     *
     * @return the value of stat_ajxx.sapzrsfzh
     *
     * @mbg.generated
     */
    public String getSapzrsfzh() {
        return sapzrsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sapzrsfzh
     *
     * @param sapzrsfzh the value for stat_ajxx.sapzrsfzh
     *
     * @mbg.generated
     */
    public void setSapzrsfzh(String sapzrsfzh) {
        this.sapzrsfzh = sapzrsfzh == null ? null : sapzrsfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sapzrxm
     *
     * @return the value of stat_ajxx.sapzrxm
     *
     * @mbg.generated
     */
    public String getSapzrxm() {
        return sapzrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sapzrxm
     *
     * @param sapzrxm the value for stat_ajxx.sapzrxm
     *
     * @mbg.generated
     */
    public void setSapzrxm(String sapzrxm) {
        this.sapzrxm = sapzrxm == null ? null : sapzrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.bjsj
     *
     * @return the value of stat_ajxx.bjsj
     *
     * @mbg.generated
     */
    public String getBjsj() {
        return bjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.bjsj
     *
     * @param bjsj the value for stat_ajxx.bjsj
     *
     * @mbg.generated
     */
    public void setBjsj(String bjsj) {
        this.bjsj = bjsj == null ? null : bjsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.bjsj_dt
     *
     * @return the value of stat_ajxx.bjsj_dt
     *
     * @mbg.generated
     */
    public Date getBjsjDt() {
        return bjsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.bjsj_dt
     *
     * @param bjsjDt the value for stat_ajxx.bjsj_dt
     *
     * @mbg.generated
     */
    public void setBjsjDt(Date bjsjDt) {
        this.bjsjDt = bjsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.bjsj_int
     *
     * @return the value of stat_ajxx.bjsj_int
     *
     * @mbg.generated
     */
    public Integer getBjsjInt() {
        return bjsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.bjsj_int
     *
     * @param bjsjInt the value for stat_ajxx.bjsj_int
     *
     * @mbg.generated
     */
    public void setBjsjInt(Integer bjsjInt) {
        this.bjsjInt = bjsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.sfyzj
     *
     * @return the value of stat_ajxx.sfyzj
     *
     * @mbg.generated
     */
    public String getSfyzj() {
        return sfyzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.sfyzj
     *
     * @param sfyzj the value for stat_ajxx.sfyzj
     *
     * @mbg.generated
     */
    public void setSfyzj(String sfyzj) {
        this.sfyzj = sfyzj == null ? null : sfyzj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.op_type
     *
     * @return the value of stat_ajxx.op_type
     *
     * @mbg.generated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.op_type
     *
     * @param opType the value for stat_ajxx.op_type
     *
     * @mbg.generated
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.time_stamp
     *
     * @return the value of stat_ajxx.time_stamp
     *
     * @mbg.generated
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.time_stamp
     *
     * @param timeStamp the value for stat_ajxx.time_stamp
     *
     * @mbg.generated
     */
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp == null ? null : timeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.dwd_yxbz
     *
     * @return the value of stat_ajxx.dwd_yxbz
     *
     * @mbg.generated
     */
    public String getDwdYxbz() {
        return dwdYxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.dwd_yxbz
     *
     * @param dwdYxbz the value for stat_ajxx.dwd_yxbz
     *
     * @mbg.generated
     */
    public void setDwdYxbz(String dwdYxbz) {
        this.dwdYxbz = dwdYxbz == null ? null : dwdYxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.dwd_zjid
     *
     * @return the value of stat_ajxx.dwd_zjid
     *
     * @mbg.generated
     */
    public String getDwdZjid() {
        return dwdZjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.dwd_zjid
     *
     * @param dwdZjid the value for stat_ajxx.dwd_zjid
     *
     * @mbg.generated
     */
    public void setDwdZjid(String dwdZjid) {
        this.dwdZjid = dwdZjid == null ? null : dwdZjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.dwd_loadtime
     *
     * @return the value of stat_ajxx.dwd_loadtime
     *
     * @mbg.generated
     */
    public String getDwdLoadtime() {
        return dwdLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.dwd_loadtime
     *
     * @param dwdLoadtime the value for stat_ajxx.dwd_loadtime
     *
     * @mbg.generated
     */
    public void setDwdLoadtime(String dwdLoadtime) {
        this.dwdLoadtime = dwdLoadtime == null ? null : dwdLoadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.dwd_upDateTime
     *
     * @return the value of stat_ajxx.dwd_upDateTime
     *
     * @mbg.generated
     */
    public String getDwdUpdatetime() {
        return dwdUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.dwd_upDateTime
     *
     * @param dwdUpdatetime the value for stat_ajxx.dwd_upDateTime
     *
     * @mbg.generated
     */
    public void setDwdUpdatetime(String dwdUpdatetime) {
        this.dwdUpdatetime = dwdUpdatetime == null ? null : dwdUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.dep_code
     *
     * @return the value of stat_ajxx.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.dep_code
     *
     * @param depCode the value for stat_ajxx.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.source_code
     *
     * @return the value of stat_ajxx.source_code
     *
     * @mbg.generated
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.source_code
     *
     * @param sourceCode the value for stat_ajxx.source_code
     *
     * @mbg.generated
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.source_code_single
     *
     * @return the value of stat_ajxx.source_code_single
     *
     * @mbg.generated
     */
    public String getSourceCodeSingle() {
        return sourceCodeSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.source_code_single
     *
     * @param sourceCodeSingle the value for stat_ajxx.source_code_single
     *
     * @mbg.generated
     */
    public void setSourceCodeSingle(String sourceCodeSingle) {
        this.sourceCodeSingle = sourceCodeSingle == null ? null : sourceCodeSingle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.source_kind
     *
     * @return the value of stat_ajxx.source_kind
     *
     * @mbg.generated
     */
    public String getSourceKind() {
        return sourceKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.source_kind
     *
     * @param sourceKind the value for stat_ajxx.source_kind
     *
     * @mbg.generated
     */
    public void setSourceKind(String sourceKind) {
        this.sourceKind = sourceKind == null ? null : sourceKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.source_kind1
     *
     * @return the value of stat_ajxx.source_kind1
     *
     * @mbg.generated
     */
    public String getSourceKind1() {
        return sourceKind1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.source_kind1
     *
     * @param sourceKind1 the value for stat_ajxx.source_kind1
     *
     * @mbg.generated
     */
    public void setSourceKind1(String sourceKind1) {
        this.sourceKind1 = sourceKind1 == null ? null : sourceKind1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_ajxx.source_kind2
     *
     * @return the value of stat_ajxx.source_kind2
     *
     * @mbg.generated
     */
    public String getSourceKind2() {
        return sourceKind2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_ajxx.source_kind2
     *
     * @param sourceKind2 the value for stat_ajxx.source_kind2
     *
     * @mbg.generated
     */
    public void setSourceKind2(String sourceKind2) {
        this.sourceKind2 = sourceKind2 == null ? null : sourceKind2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_ajxx
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ajbh=").append(ajbh);
        sb.append(", jqbh=").append(jqbh);
        sb.append(", ajmc=").append(ajmc);
        sb.append(", jyaq=").append(jyaq);
        sb.append(", aybh=").append(aybh);
        sb.append(", zbrXm=").append(zbrXm);
        sb.append(", zbrSfzh=").append(zbrSfzh);
        sb.append(", zbdwMc=").append(zbdwMc);
        sb.append(", zbdwBh=").append(zbdwBh);
        sb.append(", zbdwXtbh=").append(zbdwXtbh);
        sb.append(", zbdwQydm=").append(zbdwQydm);
        sb.append(", zbdwQy=").append(zbdwQy);
        sb.append(", zbdwDsdm=").append(zbdwDsdm);
        sb.append(", slsj=").append(slsj);
        sb.append(", slsjDt=").append(slsjDt);
        sb.append(", slsjInt=").append(slsjInt);
        sb.append(", sarq=").append(sarq);
        sb.append(", sarqDt=").append(sarqDt);
        sb.append(", sarqInt=").append(sarqInt);
        sb.append(", sapzsj=").append(sapzsj);
        sb.append(", sapzsjDt=").append(sapzsjDt);
        sb.append(", sapzsjInt=").append(sapzsjInt);
        sb.append(", larq=").append(larq);
        sb.append(", larqDt=").append(larqDt);
        sb.append(", larqInt=").append(larqInt);
        sb.append(", lapzsj=").append(lapzsj);
        sb.append(", lapzsjDt=").append(lapzsjDt);
        sb.append(", lapzsjInt=").append(lapzsjInt);
        sb.append(", sfqdkb=").append(sfqdkb);
        sb.append(", ajlydm=").append(ajlydm);
        sb.append(", ajly=").append(ajly);
        sb.append(", sfja=").append(sfja);
        sb.append(", ajlxdm=").append(ajlxdm);
        sb.append(", ajlx=").append(ajlx);
        sb.append(", shztdm=").append(shztdm);
        sb.append(", shzt=").append(shzt);
        sb.append(", ajztdm=").append(ajztdm);
        sb.append(", ajzt=").append(ajzt);
        sb.append(", gdqk=").append(gdqk);
        sb.append(", ajmjdm=").append(ajmjdm);
        sb.append(", ajmj=").append(ajmj);
        sb.append(", aymc=").append(aymc);
        sb.append(", fasjsx=").append(fasjsx);
        sb.append(", fasjsxDt=").append(fasjsxDt);
        sb.append(", fasjsxInt=").append(fasjsxInt);
        sb.append(", fadd=").append(fadd);
        sb.append(", jasj=").append(jasj);
        sb.append(", jasjDt=").append(jasjDt);
        sb.append(", jasjInt=").append(jasjInt);
        sb.append(", fasjxx=").append(fasjxx);
        sb.append(", fasjxxDt=").append(fasjxxDt);
        sb.append(", fasjxxInt=").append(fasjxxInt);
        sb.append(", faddXzqhdm=").append(faddXzqhdm);
        sb.append(", faddXzqh=").append(faddXzqh);
        sb.append(", lrsj=").append(lrsj);
        sb.append(", lrsjDt=").append(lrsjDt);
        sb.append(", lrsjInt=").append(lrsjInt);
        sb.append(", lrrSfzh=").append(lrrSfzh);
        sb.append(", xgrSfzh=").append(xgrSfzh);
        sb.append(", xgsj=").append(xgsj);
        sb.append(", xgsjDt=").append(xgsjDt);
        sb.append(", xgsjInt=").append(xgsjInt);
        sb.append(", isdel=").append(isdel);
        sb.append(", dataFlag=").append(dataFlag);
        sb.append(", dsdm=").append(dsdm);
        sb.append(", sfcs=").append(sfcs);
        sb.append(", scshsj=").append(scshsj);
        sb.append(", scshsjDt=").append(scshsjDt);
        sb.append(", scshsjInt=").append(scshsjInt);
        sb.append(", scshrXm=").append(scshrXm);
        sb.append(", scshrSfzh=").append(scshrSfzh);
        sb.append(", zgqkdm=").append(zgqkdm);
        sb.append(", zgqk=").append(zgqk);
        sb.append(", sjsj=").append(sjsj);
        sb.append(", sjsjDt=").append(sjsjDt);
        sb.append(", sjsjInt=").append(sjsjInt);
        sb.append(", czjgdm=").append(czjgdm);
        sb.append(", czjg=").append(czjg);
        sb.append(", sfxc=").append(sfxc);
        sb.append(", sfkjhz=").append(sfkjhz);
        sb.append(", ajbsdm=").append(ajbsdm);
        sb.append(", ajbs=").append(ajbs);
        sb.append(", xlaymc=").append(xlaymc);
        sb.append(", xlaybh=").append(xlaybh);
        sb.append(", sapzrsfzh=").append(sapzrsfzh);
        sb.append(", sapzrxm=").append(sapzrxm);
        sb.append(", bjsj=").append(bjsj);
        sb.append(", bjsjDt=").append(bjsjDt);
        sb.append(", bjsjInt=").append(bjsjInt);
        sb.append(", sfyzj=").append(sfyzj);
        sb.append(", opType=").append(opType);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", dwdYxbz=").append(dwdYxbz);
        sb.append(", dwdZjid=").append(dwdZjid);
        sb.append(", dwdLoadtime=").append(dwdLoadtime);
        sb.append(", dwdUpdatetime=").append(dwdUpdatetime);
        sb.append(", depCode=").append(depCode);
        sb.append(", sourceCode=").append(sourceCode);
        sb.append(", sourceCodeSingle=").append(sourceCodeSingle);
        sb.append(", sourceKind=").append(sourceKind);
        sb.append(", sourceKind1=").append(sourceKind1);
        sb.append(", sourceKind2=").append(sourceKind2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}