package com.dao.entity.zjstat;

import com.dao.entity.sys.ComColumn;

import java.io.Serializable;

public class ZbAssessColor extends ComColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_assess_color.id
     *
     * @mbg.generated
     */
    private String id;

    private String zbAssessMainRefid;

    private String depCode;

    private String color;

    private String valueBegin;

    private String valueEnd;

    private String remark1;

    private String remark2;

    private String assessName;

    public String getAssessName() {
        return assessName;
    }

    public void setAssessName(String assessName) {
        this.assessName = assessName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zb_assess_color
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.id
     *
     * @return the value of zb_assess_color.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.id
     *
     * @param id the value for zb_assess_color.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.zb_assess_main_refid
     *
     * @return the value of zb_assess_color.zb_assess_main_refid
     *
     * @mbg.generated
     */
    public String getZbAssessMainRefid() {
        return zbAssessMainRefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.zb_assess_main_refid
     *
     * @param zbAssessMainRefid the value for zb_assess_color.zb_assess_main_refid
     *
     * @mbg.generated
     */
    public void setZbAssessMainRefid(String zbAssessMainRefid) {
        this.zbAssessMainRefid = zbAssessMainRefid == null ? null : zbAssessMainRefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.dep_code
     *
     * @return the value of zb_assess_color.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.dep_code
     *
     * @param depCode the value for zb_assess_color.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.color
     *
     * @return the value of zb_assess_color.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.color
     *
     * @param color the value for zb_assess_color.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.value_begin
     *
     * @return the value of zb_assess_color.value_begin
     *
     * @mbg.generated
     */
    public String getValueBegin() {
        return valueBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.value_begin
     *
     * @param valueBegin the value for zb_assess_color.value_begin
     *
     * @mbg.generated
     */
    public void setValueBegin(String valueBegin) {
        this.valueBegin = valueBegin == null ? null : valueBegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.value_end
     *
     * @return the value of zb_assess_color.value_end
     *
     * @mbg.generated
     */
    public String getValueEnd() {
        return valueEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.value_end
     *
     * @param valueEnd the value for zb_assess_color.value_end
     *
     * @mbg.generated
     */
    public void setValueEnd(String valueEnd) {
        this.valueEnd = valueEnd == null ? null : valueEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.remark1
     *
     * @return the value of zb_assess_color.remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.remark1
     *
     * @param remark1 the value for zb_assess_color.remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_color.remark2
     *
     * @return the value of zb_assess_color.remark2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_color.remark2
     *
     * @param remark2 the value for zb_assess_color.remark2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_assess_color
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", zbAssessMainRefid=").append(zbAssessMainRefid);
        sb.append(", depCode=").append(depCode);
        sb.append(", color=").append(color);
        sb.append(", valueBegin=").append(valueBegin);
        sb.append(", valueEnd=").append(valueEnd);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}