package com.dao.entity.zjstat;

import com.dao.entity.sys.ComColumn;

import java.io.Serializable;
import java.math.BigDecimal;

public class ZbAssessDetail1 extends ComColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_assess_detail1.id
     *
     * @mbg.generated
     */
    private String id;

    private String depCode;

    private String zbAssessMainRefid;

    private String name;

    private String fieldName;

    private String fieldNameValue;

    private String fieldShowName;

    private String zbCalculationConfigRefid;

    private BigDecimal weight;

    private BigDecimal weightOk;

    private Integer calSort1;

    private Integer calSort2;

    private Integer calSort3;

    private String remark1;

    private String remark2;

    private String calculationName;
    private String calculationConfigName;

    private String field;

    private String formulae;

    public String getCalculationConfigName() {
        return calculationConfigName;
    }

    public void setCalculationConfigName(String calculationConfigName) {
        this.calculationConfigName = calculationConfigName;
    }

    public String getFieldShowName() {
        return fieldShowName;
    }

    public void setFieldShowName(String fieldShowName) {
        this.fieldShowName = fieldShowName;
    }

    public String getFormulae() {
        return formulae;
    }

    public void setFormulae(String formulae) {
        this.formulae = formulae;
    }

    public String getCalculationName() {
        return calculationName;
    }

    public void setCalculationName(String calculationName) {
        this.calculationName = calculationName;
    }

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zb_assess_detail1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.id
     *
     * @return the value of zb_assess_detail1.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.id
     *
     * @param id the value for zb_assess_detail1.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.dep_code
     *
     * @return the value of zb_assess_detail1.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.dep_code
     *
     * @param depCode the value for zb_assess_detail1.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.zb_assess_main_refid
     *
     * @return the value of zb_assess_detail1.zb_assess_main_refid
     *
     * @mbg.generated
     */
    public String getZbAssessMainRefid() {
        return zbAssessMainRefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.zb_assess_main_refid
     *
     * @param zbAssessMainRefid the value for zb_assess_detail1.zb_assess_main_refid
     *
     * @mbg.generated
     */
    public void setZbAssessMainRefid(String zbAssessMainRefid) {
        this.zbAssessMainRefid = zbAssessMainRefid == null ? null : zbAssessMainRefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.name
     *
     * @return the value of zb_assess_detail1.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.name
     *
     * @param name the value for zb_assess_detail1.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.field_name
     *
     * @return the value of zb_assess_detail1.field_name
     *
     * @mbg.generated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.field_name
     *
     * @param fieldName the value for zb_assess_detail1.field_name
     *
     * @mbg.generated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.field_name_value
     *
     * @return the value of zb_assess_detail1.field_name_value
     *
     * @mbg.generated
     */
    public String getFieldNameValue() {
        return fieldNameValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.field_name_value
     *
     * @param fieldNameValue the value for zb_assess_detail1.field_name_value
     *
     * @mbg.generated
     */
    public void setFieldNameValue(String fieldNameValue) {
        this.fieldNameValue = fieldNameValue == null ? null : fieldNameValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.zb_calculation_config_refid
     *
     * @return the value of zb_assess_detail1.zb_calculation_config_refid
     *
     * @mbg.generated
     */
    public String getZbCalculationConfigRefid() {
        return zbCalculationConfigRefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.zb_calculation_config_refid
     *
     * @param zbCalculationConfigRefid the value for zb_assess_detail1.zb_calculation_config_refid
     *
     * @mbg.generated
     */
    public void setZbCalculationConfigRefid(String zbCalculationConfigRefid) {
        this.zbCalculationConfigRefid = zbCalculationConfigRefid == null ? null : zbCalculationConfigRefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.weight
     *
     * @return the value of zb_assess_detail1.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.weight
     *
     * @param weight the value for zb_assess_detail1.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.weight_ok
     *
     * @return the value of zb_assess_detail1.weight_ok
     *
     * @mbg.generated
     */
    public BigDecimal getWeightOk() {
        return weightOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.weight_ok
     *
     * @param weightOk the value for zb_assess_detail1.weight_ok
     *
     * @mbg.generated
     */
    public void setWeightOk(BigDecimal weightOk) {
        this.weightOk = weightOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.cal_sort1
     *
     * @return the value of zb_assess_detail1.cal_sort1
     *
     * @mbg.generated
     */
    public Integer getCalSort1() {
        return calSort1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.cal_sort1
     *
     * @param calSort1 the value for zb_assess_detail1.cal_sort1
     *
     * @mbg.generated
     */
    public void setCalSort1(Integer calSort1) {
        this.calSort1 = calSort1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.cal_sort2
     *
     * @return the value of zb_assess_detail1.cal_sort2
     *
     * @mbg.generated
     */
    public Integer getCalSort2() {
        return calSort2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.cal_sort2
     *
     * @param calSort2 the value for zb_assess_detail1.cal_sort2
     *
     * @mbg.generated
     */
    public void setCalSort2(Integer calSort2) {
        this.calSort2 = calSort2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.cal_sort3
     *
     * @return the value of zb_assess_detail1.cal_sort3
     *
     * @mbg.generated
     */
    public Integer getCalSort3() {
        return calSort3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.cal_sort3
     *
     * @param calSort3 the value for zb_assess_detail1.cal_sort3
     *
     * @mbg.generated
     */
    public void setCalSort3(Integer calSort3) {
        this.calSort3 = calSort3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.remark1
     *
     * @return the value of zb_assess_detail1.remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.remark1
     *
     * @param remark1 the value for zb_assess_detail1.remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_detail1.remark2
     *
     * @return the value of zb_assess_detail1.remark2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_detail1.remark2
     *
     * @param remark2 the value for zb_assess_detail1.remark2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zb_assess_detail1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", depCode=").append(depCode);
        sb.append(", zbAssessMainRefid=").append(zbAssessMainRefid);
        sb.append(", name=").append(name);
        sb.append(", fieldName=").append(fieldName);
        sb.append(", fieldNameValue=").append(fieldNameValue);
        sb.append(", zbCalculationConfigRefid=").append(zbCalculationConfigRefid);
        sb.append(", weight=").append(weight);
        sb.append(", weightOk=").append(weightOk);
        sb.append(", calSort1=").append(calSort1);
        sb.append(", calSort2=").append(calSort2);
        sb.append(", calSort3=").append(calSort3);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}