package com.dao.entity.zjstat;

import com.dao.entity.sys.ComColumn;

import java.io.Serializable;
import java.util.List;

public class ZbAssessMain extends ComColumn implements Serializable {

    private String id;

    private String depCode;

    private String statDepCode;

    private String name;

    private String createTime;

    private String startTime;

    private String createName;

    private String startClass;

    private Integer state;

    private String discription;

    private String remark1;

    private String remark2;

    private String remark3;

    private List<ZbAssessDetail1> zbAssessDetail1List;

    private List<ZbAssessDetail2> zbAssessDetail2List;

    private List<ZbAssessColor> zbAssessColorList;

    private String statDepName;

    private String createPerson;

    public String getCreatePerson() {
        return createPerson;
    }

    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    public String getStatDepName() {
        return statDepName;
    }

    public void setStatDepName(String statDepName) {
        this.statDepName = statDepName;
    }

    public List<ZbAssessColor> getZbAssessColorList() {
        return zbAssessColorList;
    }

    public void setZbAssessColorList(List<ZbAssessColor> zbAssessColorList) {
        this.zbAssessColorList = zbAssessColorList;
    }

    public List<ZbAssessDetail1> getZbAssessDetail1List() {
        return zbAssessDetail1List;
    }

    public void setZbAssessDetail1List(List<ZbAssessDetail1> zbAssessDetail1List) {
        this.zbAssessDetail1List = zbAssessDetail1List;
    }

    public List<ZbAssessDetail2> getZbAssessDetail2List() {
        return zbAssessDetail2List;
    }

    public void setZbAssessDetail2List(List<ZbAssessDetail2> zbAssessDetail2List) {
        this.zbAssessDetail2List = zbAssessDetail2List;
    }

    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getDepCode() {
        return depCode;
    }

    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.stat_dep_code
     *
     * @return the value of zb_assess_main.stat_dep_code
     *
     * @mbg.generated
     */
    public String getStatDepCode() {
        return statDepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.stat_dep_code
     *
     * @param statDepCode the value for zb_assess_main.stat_dep_code
     *
     * @mbg.generated
     */
    public void setStatDepCode(String statDepCode) {
        this.statDepCode = statDepCode == null ? null : statDepCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.name
     *
     * @return the value of zb_assess_main.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.name
     *
     * @param name the value for zb_assess_main.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.create_time
     *
     * @return the value of zb_assess_main.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.create_time
     *
     * @param createTime the value for zb_assess_main.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.start_time
     *
     * @return the value of zb_assess_main.start_time
     *
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.start_time
     *
     * @param startTime the value for zb_assess_main.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.create_name
     *
     * @return the value of zb_assess_main.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.create_name
     *
     * @param createName the value for zb_assess_main.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.start_class
     *
     * @return the value of zb_assess_main.start_class
     *
     * @mbg.generated
     */
    public String getStartClass() {
        return startClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.start_class
     *
     * @param startClass the value for zb_assess_main.start_class
     *
     * @mbg.generated
     */
    public void setStartClass(String startClass) {
        this.startClass = startClass == null ? null : startClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.state
     *
     * @return the value of zb_assess_main.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_assess_main.state
     *
     * @param state the value for zb_assess_main.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_assess_main.discription
     *
     * @return the value of zb_assess_main.discription
     *
     * @mbg.generated
     */
    public String getDiscription() {
        return discription;
    }

    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }

    public String getRemark1() {
        return remark1;
    }

    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    public String getRemark2() {
        return remark2;
    }

    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    public String getRemark3() {
        return remark3;
    }

    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", depCode=").append(depCode);
        sb.append(", statDepCode=").append(statDepCode);
        sb.append(", name=").append(name);
        sb.append(", createTime=").append(createTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", createName=").append(createName);
        sb.append(", startClass=").append(startClass);
        sb.append(", state=").append(state);
        sb.append(", discription=").append(discription);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", remark3=").append(remark3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}