package com.dao.entity.syserp;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.AccountID
     *
     * @mbg.generated
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.ShortName
     *
     * @mbg.generated
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Tax
     *
     * @mbg.generated
     */
    private String tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Corporation
     *
     * @mbg.generated
     */
    private String corporation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.PostalCode
     *
     * @mbg.generated
     */
    private String postalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.State
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.RegCode
     *
     * @mbg.generated
     */
    private String regcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.SysBeginDate
     *
     * @mbg.generated
     */
    private Date sysbegindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.SysEndDate
     *
     * @mbg.generated
     */
    private Date sysenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.IsMainAccount
     *
     * @mbg.generated
     */
    private Integer ismainaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Picture
     *
     * @mbg.generated
     */
    private byte[] picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Account.Popedom
     *
     * @mbg.generated
     */
    private byte[] popedom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.AccountID
     *
     * @return the value of Account.AccountID
     *
     * @mbg.generated
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.AccountID
     *
     * @param accountid the value for Account.AccountID
     *
     * @mbg.generated
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Name
     *
     * @return the value of Account.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Name
     *
     * @param name the value for Account.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.ShortName
     *
     * @return the value of Account.ShortName
     *
     * @mbg.generated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.ShortName
     *
     * @param shortname the value for Account.ShortName
     *
     * @mbg.generated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Tax
     *
     * @return the value of Account.Tax
     *
     * @mbg.generated
     */
    public String getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Tax
     *
     * @param tax the value for Account.Tax
     *
     * @mbg.generated
     */
    public void setTax(String tax) {
        this.tax = tax == null ? null : tax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Account
     *
     * @return the value of Account.Account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Account
     *
     * @param account the value for Account.Account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Bank
     *
     * @return the value of Account.Bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Bank
     *
     * @param bank the value for Account.Bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Corporation
     *
     * @return the value of Account.Corporation
     *
     * @mbg.generated
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Corporation
     *
     * @param corporation the value for Account.Corporation
     *
     * @mbg.generated
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Address
     *
     * @return the value of Account.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Address
     *
     * @param address the value for Account.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.PostalCode
     *
     * @return the value of Account.PostalCode
     *
     * @mbg.generated
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.PostalCode
     *
     * @param postalcode the value for Account.PostalCode
     *
     * @mbg.generated
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Phone
     *
     * @return the value of Account.Phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Phone
     *
     * @param phone the value for Account.Phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Email
     *
     * @return the value of Account.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Email
     *
     * @param email the value for Account.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Fax
     *
     * @return the value of Account.Fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Fax
     *
     * @param fax the value for Account.Fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.State
     *
     * @return the value of Account.State
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.State
     *
     * @param state the value for Account.State
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Remark
     *
     * @return the value of Account.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Remark
     *
     * @param remark the value for Account.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.RegCode
     *
     * @return the value of Account.RegCode
     *
     * @mbg.generated
     */
    public String getRegcode() {
        return regcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.RegCode
     *
     * @param regcode the value for Account.RegCode
     *
     * @mbg.generated
     */
    public void setRegcode(String regcode) {
        this.regcode = regcode == null ? null : regcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.SysBeginDate
     *
     * @return the value of Account.SysBeginDate
     *
     * @mbg.generated
     */
    public Date getSysbegindate() {
        return sysbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.SysBeginDate
     *
     * @param sysbegindate the value for Account.SysBeginDate
     *
     * @mbg.generated
     */
    public void setSysbegindate(Date sysbegindate) {
        this.sysbegindate = sysbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.SysEndDate
     *
     * @return the value of Account.SysEndDate
     *
     * @mbg.generated
     */
    public Date getSysenddate() {
        return sysenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.SysEndDate
     *
     * @param sysenddate the value for Account.SysEndDate
     *
     * @mbg.generated
     */
    public void setSysenddate(Date sysenddate) {
        this.sysenddate = sysenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.IsMainAccount
     *
     * @return the value of Account.IsMainAccount
     *
     * @mbg.generated
     */
    public Integer getIsmainaccount() {
        return ismainaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.IsMainAccount
     *
     * @param ismainaccount the value for Account.IsMainAccount
     *
     * @mbg.generated
     */
    public void setIsmainaccount(Integer ismainaccount) {
        this.ismainaccount = ismainaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Picture
     *
     * @return the value of Account.Picture
     *
     * @mbg.generated
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Picture
     *
     * @param picture the value for Account.Picture
     *
     * @mbg.generated
     */
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Account.Popedom
     *
     * @return the value of Account.Popedom
     *
     * @mbg.generated
     */
    public byte[] getPopedom() {
        return popedom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Account.Popedom
     *
     * @param popedom the value for Account.Popedom
     *
     * @mbg.generated
     */
    public void setPopedom(byte[] popedom) {
        this.popedom = popedom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", accountid=").append(accountid);
        sb.append(", name=").append(name);
        sb.append(", shortname=").append(shortname);
        sb.append(", tax=").append(tax);
        sb.append(", account=").append(account);
        sb.append(", bank=").append(bank);
        sb.append(", corporation=").append(corporation);
        sb.append(", Address=").append(address);
        sb.append(", postalcode=").append(postalcode);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", fax=").append(fax);
        sb.append(", state=").append(state);
        sb.append(", remark=").append(remark);
        sb.append(", regcode=").append(regcode);
        sb.append(", sysbegindate=").append(sysbegindate);
        sb.append(", sysenddate=").append(sysenddate);
        sb.append(", ismainaccount=").append(ismainaccount);
        sb.append(", picture=").append(picture);
        sb.append(", popedom=").append(popedom);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}