package com.dao.entity.mock;

import java.io.Serializable;
import java.math.BigDecimal;

public class MockMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.chinese
     *
     * @mbg.generated
     */
    private String chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.english
     *
     * @mbg.generated
     */
    private String english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.num
     *
     * @mbg.generated
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.tota
     *
     * @mbg.generated
     */
    private BigDecimal tota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.diff
     *
     * @mbg.generated
     */
    private BigDecimal diff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mock_message.phy
     *
     * @mbg.generated
     */
    private BigDecimal phy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mock_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.id
     *
     * @return the value of mock_message.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.id
     *
     * @param id the value for mock_message.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.name
     *
     * @return the value of mock_message.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.name
     *
     * @param name the value for mock_message.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.chinese
     *
     * @return the value of mock_message.chinese
     *
     * @mbg.generated
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.chinese
     *
     * @param chinese the value for mock_message.chinese
     *
     * @mbg.generated
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.english
     *
     * @return the value of mock_message.english
     *
     * @mbg.generated
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.english
     *
     * @param english the value for mock_message.english
     *
     * @mbg.generated
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.num
     *
     * @return the value of mock_message.num
     *
     * @mbg.generated
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.num
     *
     * @param num the value for mock_message.num
     *
     * @mbg.generated
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.tota
     *
     * @return the value of mock_message.tota
     *
     * @mbg.generated
     */
    public BigDecimal getTota() {
        return tota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.tota
     *
     * @param tota the value for mock_message.tota
     *
     * @mbg.generated
     */
    public void setTota(BigDecimal tota) {
        this.tota = tota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.diff
     *
     * @return the value of mock_message.diff
     *
     * @mbg.generated
     */
    public BigDecimal getDiff() {
        return diff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.diff
     *
     * @param diff the value for mock_message.diff
     *
     * @mbg.generated
     */
    public void setDiff(BigDecimal diff) {
        this.diff = diff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mock_message.phy
     *
     * @return the value of mock_message.phy
     *
     * @mbg.generated
     */
    public BigDecimal getPhy() {
        return phy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mock_message.phy
     *
     * @param phy the value for mock_message.phy
     *
     * @mbg.generated
     */
    public void setPhy(BigDecimal phy) {
        this.phy = phy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mock_message
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", chinese=").append(chinese);
        sb.append(", english=").append(english);
        sb.append(", num=").append(num);
        sb.append(", tota=").append(tota);
        sb.append(", diff=").append(diff);
        sb.append(", phy=").append(phy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}