package com.dao.db1.zjstat;

import com.dao.entity.zjstat.StatPerpleSrcCzrk;

import java.util.List;
import java.util.Map;

public interface StatPerpleSrcCzrkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_perple_src_czrk
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_perple_src_czrk
     *
     * @mbg.generated
     */
    int insert(StatPerpleSrcCzrk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_perple_src_czrk
     *
     * @mbg.generated
     */
    StatPerpleSrcCzrk selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_perple_src_czrk
     *
     * @mbg.generated
     */
    List<StatPerpleSrcCzrk> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_perple_src_czrk
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StatPerpleSrcCzrk record);

    List<StatPerpleSrcCzrk> search(Map<String, Object> queryMap);

    Integer sum(Map<String, Object> queryMap);

    StatPerpleSrcCzrk selectBySfzh(String sfzh);
}