package com.dao.db1.system.entity;

import com.dao.entity.sys.ComColumn;

import java.io.Serializable;
import java.math.BigDecimal;

public class StatDicTimes extends ComColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.dep_code
     *
     * @mbg.generated
     */
    private String depCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.dic_code
     *
     * @mbg.generated
     */
    private String dicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.dic_name
     *
     * @mbg.generated
     */
    private String dicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.statr_time1_type
     *
     * @mbg.generated
     */
    private String statrTime1Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.start_time1_class
     *
     * @mbg.generated
     */
    private String startTime1Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.start_time1
     *
     * @mbg.generated
     */
    private String startTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time1_type
     *
     * @mbg.generated
     */
    private String endTime1Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time1_class
     *
     * @mbg.generated
     */
    private String endTime1Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time1
     *
     * @mbg.generated
     */
    private String endTime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.statr_time2_type
     *
     * @mbg.generated
     */
    private String statrTime2Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.start_time2_class
     *
     * @mbg.generated
     */
    private String startTime2Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.start_time2
     *
     * @mbg.generated
     */
    private String startTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time2_type
     *
     * @mbg.generated
     */
    private String endTime2Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time2_class
     *
     * @mbg.generated
     */
    private String endTime2Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time2
     *
     * @mbg.generated
     */
    private String endTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.start_time3_class
     *
     * @mbg.generated
     */
    private String startTime3Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.statr_time3_type
     *
     * @mbg.generated
     */
    private String statrTime3Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.start_time3
     *
     * @mbg.generated
     */
    private String startTime3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time3_type
     *
     * @mbg.generated
     */
    private String endTime3Type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time3_class
     *
     * @mbg.generated
     */
    private String endTime3Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.end_time3
     *
     * @mbg.generated
     */
    private String endTime3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.dic_explain
     *
     * @mbg.generated
     */
    private String dicExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.dic_type
     *
     * @mbg.generated
     */
    private String dicType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.dic_sort
     *
     * @mbg.generated
     */
    private Integer dicSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.remark1
     *
     * @mbg.generated
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.remark2
     *
     * @mbg.generated
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.multiple1
     *
     * @mbg.generated
     */
    private BigDecimal multiple1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.multiple2
     *
     * @mbg.generated
     */
    private BigDecimal multiple2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.multiple3
     *
     * @mbg.generated
     */
    private BigDecimal multiple3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_dic_times.multiple4
     *
     * @mbg.generated
     */
    private BigDecimal multiple4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stat_dic_times
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    private String dicTypeName;

    public String getDicTypeName() {
        return dicTypeName;
    }

    public void setDicTypeName(String dicTypeName) {
        this.dicTypeName = dicTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.id
     *
     * @return the value of stat_dic_times.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.id
     *
     * @param id the value for stat_dic_times.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.dep_code
     *
     * @return the value of stat_dic_times.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.dep_code
     *
     * @param depCode the value for stat_dic_times.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.dic_code
     *
     * @return the value of stat_dic_times.dic_code
     *
     * @mbg.generated
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.dic_code
     *
     * @param dicCode the value for stat_dic_times.dic_code
     *
     * @mbg.generated
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.dic_name
     *
     * @return the value of stat_dic_times.dic_name
     *
     * @mbg.generated
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.dic_name
     *
     * @param dicName the value for stat_dic_times.dic_name
     *
     * @mbg.generated
     */
    public void setDicName(String dicName) {
        this.dicName = dicName == null ? null : dicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.statr_time1_type
     *
     * @return the value of stat_dic_times.statr_time1_type
     *
     * @mbg.generated
     */
    public String getStatrTime1Type() {
        return statrTime1Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.statr_time1_type
     *
     * @param statrTime1Type the value for stat_dic_times.statr_time1_type
     *
     * @mbg.generated
     */
    public void setStatrTime1Type(String statrTime1Type) {
        this.statrTime1Type = statrTime1Type == null ? null : statrTime1Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.start_time1_class
     *
     * @return the value of stat_dic_times.start_time1_class
     *
     * @mbg.generated
     */
    public String getStartTime1Class() {
        return startTime1Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.start_time1_class
     *
     * @param startTime1Class the value for stat_dic_times.start_time1_class
     *
     * @mbg.generated
     */
    public void setStartTime1Class(String startTime1Class) {
        this.startTime1Class = startTime1Class == null ? null : startTime1Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.start_time1
     *
     * @return the value of stat_dic_times.start_time1
     *
     * @mbg.generated
     */
    public String getStartTime1() {
        return startTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.start_time1
     *
     * @param startTime1 the value for stat_dic_times.start_time1
     *
     * @mbg.generated
     */
    public void setStartTime1(String startTime1) {
        this.startTime1 = startTime1 == null ? null : startTime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time1_type
     *
     * @return the value of stat_dic_times.end_time1_type
     *
     * @mbg.generated
     */
    public String getEndTime1Type() {
        return endTime1Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time1_type
     *
     * @param endTime1Type the value for stat_dic_times.end_time1_type
     *
     * @mbg.generated
     */
    public void setEndTime1Type(String endTime1Type) {
        this.endTime1Type = endTime1Type == null ? null : endTime1Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time1_class
     *
     * @return the value of stat_dic_times.end_time1_class
     *
     * @mbg.generated
     */
    public String getEndTime1Class() {
        return endTime1Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time1_class
     *
     * @param endTime1Class the value for stat_dic_times.end_time1_class
     *
     * @mbg.generated
     */
    public void setEndTime1Class(String endTime1Class) {
        this.endTime1Class = endTime1Class == null ? null : endTime1Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time1
     *
     * @return the value of stat_dic_times.end_time1
     *
     * @mbg.generated
     */
    public String getEndTime1() {
        return endTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time1
     *
     * @param endTime1 the value for stat_dic_times.end_time1
     *
     * @mbg.generated
     */
    public void setEndTime1(String endTime1) {
        this.endTime1 = endTime1 == null ? null : endTime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.statr_time2_type
     *
     * @return the value of stat_dic_times.statr_time2_type
     *
     * @mbg.generated
     */
    public String getStatrTime2Type() {
        return statrTime2Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.statr_time2_type
     *
     * @param statrTime2Type the value for stat_dic_times.statr_time2_type
     *
     * @mbg.generated
     */
    public void setStatrTime2Type(String statrTime2Type) {
        this.statrTime2Type = statrTime2Type == null ? null : statrTime2Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.start_time2_class
     *
     * @return the value of stat_dic_times.start_time2_class
     *
     * @mbg.generated
     */
    public String getStartTime2Class() {
        return startTime2Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.start_time2_class
     *
     * @param startTime2Class the value for stat_dic_times.start_time2_class
     *
     * @mbg.generated
     */
    public void setStartTime2Class(String startTime2Class) {
        this.startTime2Class = startTime2Class == null ? null : startTime2Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.start_time2
     *
     * @return the value of stat_dic_times.start_time2
     *
     * @mbg.generated
     */
    public String getStartTime2() {
        return startTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.start_time2
     *
     * @param startTime2 the value for stat_dic_times.start_time2
     *
     * @mbg.generated
     */
    public void setStartTime2(String startTime2) {
        this.startTime2 = startTime2 == null ? null : startTime2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time2_type
     *
     * @return the value of stat_dic_times.end_time2_type
     *
     * @mbg.generated
     */
    public String getEndTime2Type() {
        return endTime2Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time2_type
     *
     * @param endTime2Type the value for stat_dic_times.end_time2_type
     *
     * @mbg.generated
     */
    public void setEndTime2Type(String endTime2Type) {
        this.endTime2Type = endTime2Type == null ? null : endTime2Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time2_class
     *
     * @return the value of stat_dic_times.end_time2_class
     *
     * @mbg.generated
     */
    public String getEndTime2Class() {
        return endTime2Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time2_class
     *
     * @param endTime2Class the value for stat_dic_times.end_time2_class
     *
     * @mbg.generated
     */
    public void setEndTime2Class(String endTime2Class) {
        this.endTime2Class = endTime2Class == null ? null : endTime2Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time2
     *
     * @return the value of stat_dic_times.end_time2
     *
     * @mbg.generated
     */
    public String getEndTime2() {
        return endTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time2
     *
     * @param endTime2 the value for stat_dic_times.end_time2
     *
     * @mbg.generated
     */
    public void setEndTime2(String endTime2) {
        this.endTime2 = endTime2 == null ? null : endTime2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.start_time3_class
     *
     * @return the value of stat_dic_times.start_time3_class
     *
     * @mbg.generated
     */
    public String getStartTime3Class() {
        return startTime3Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.start_time3_class
     *
     * @param startTime3Class the value for stat_dic_times.start_time3_class
     *
     * @mbg.generated
     */
    public void setStartTime3Class(String startTime3Class) {
        this.startTime3Class = startTime3Class == null ? null : startTime3Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.statr_time3_type
     *
     * @return the value of stat_dic_times.statr_time3_type
     *
     * @mbg.generated
     */
    public String getStatrTime3Type() {
        return statrTime3Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.statr_time3_type
     *
     * @param statrTime3Type the value for stat_dic_times.statr_time3_type
     *
     * @mbg.generated
     */
    public void setStatrTime3Type(String statrTime3Type) {
        this.statrTime3Type = statrTime3Type == null ? null : statrTime3Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.start_time3
     *
     * @return the value of stat_dic_times.start_time3
     *
     * @mbg.generated
     */
    public String getStartTime3() {
        return startTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.start_time3
     *
     * @param startTime3 the value for stat_dic_times.start_time3
     *
     * @mbg.generated
     */
    public void setStartTime3(String startTime3) {
        this.startTime3 = startTime3 == null ? null : startTime3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time3_type
     *
     * @return the value of stat_dic_times.end_time3_type
     *
     * @mbg.generated
     */
    public String getEndTime3Type() {
        return endTime3Type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time3_type
     *
     * @param endTime3Type the value for stat_dic_times.end_time3_type
     *
     * @mbg.generated
     */
    public void setEndTime3Type(String endTime3Type) {
        this.endTime3Type = endTime3Type == null ? null : endTime3Type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time3_class
     *
     * @return the value of stat_dic_times.end_time3_class
     *
     * @mbg.generated
     */
    public String getEndTime3Class() {
        return endTime3Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time3_class
     *
     * @param endTime3Class the value for stat_dic_times.end_time3_class
     *
     * @mbg.generated
     */
    public void setEndTime3Class(String endTime3Class) {
        this.endTime3Class = endTime3Class == null ? null : endTime3Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.end_time3
     *
     * @return the value of stat_dic_times.end_time3
     *
     * @mbg.generated
     */
    public String getEndTime3() {
        return endTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.end_time3
     *
     * @param endTime3 the value for stat_dic_times.end_time3
     *
     * @mbg.generated
     */
    public void setEndTime3(String endTime3) {
        this.endTime3 = endTime3 == null ? null : endTime3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.dic_explain
     *
     * @return the value of stat_dic_times.dic_explain
     *
     * @mbg.generated
     */
    public String getDicExplain() {
        return dicExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.dic_explain
     *
     * @param dicExplain the value for stat_dic_times.dic_explain
     *
     * @mbg.generated
     */
    public void setDicExplain(String dicExplain) {
        this.dicExplain = dicExplain == null ? null : dicExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.dic_type
     *
     * @return the value of stat_dic_times.dic_type
     *
     * @mbg.generated
     */
    public String getDicType() {
        return dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.dic_type
     *
     * @param dicType the value for stat_dic_times.dic_type
     *
     * @mbg.generated
     */
    public void setDicType(String dicType) {
        this.dicType = dicType == null ? null : dicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.dic_sort
     *
     * @return the value of stat_dic_times.dic_sort
     *
     * @mbg.generated
     */
    public Integer getDicSort() {
        return dicSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.dic_sort
     *
     * @param dicSort the value for stat_dic_times.dic_sort
     *
     * @mbg.generated
     */
    public void setDicSort(Integer dicSort) {
        this.dicSort = dicSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.state
     *
     * @return the value of stat_dic_times.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.state
     *
     * @param state the value for stat_dic_times.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.remark1
     *
     * @return the value of stat_dic_times.remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.remark1
     *
     * @param remark1 the value for stat_dic_times.remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.remark2
     *
     * @return the value of stat_dic_times.remark2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.remark2
     *
     * @param remark2 the value for stat_dic_times.remark2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.multiple1
     *
     * @return the value of stat_dic_times.multiple1
     *
     * @mbg.generated
     */
    public BigDecimal getMultiple1() {
        return multiple1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.multiple1
     *
     * @param multiple1 the value for stat_dic_times.multiple1
     *
     * @mbg.generated
     */
    public void setMultiple1(BigDecimal multiple1) {
        this.multiple1 = multiple1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.multiple2
     *
     * @return the value of stat_dic_times.multiple2
     *
     * @mbg.generated
     */
    public BigDecimal getMultiple2() {
        return multiple2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.multiple2
     *
     * @param multiple2 the value for stat_dic_times.multiple2
     *
     * @mbg.generated
     */
    public void setMultiple2(BigDecimal multiple2) {
        this.multiple2 = multiple2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.multiple3
     *
     * @return the value of stat_dic_times.multiple3
     *
     * @mbg.generated
     */
    public BigDecimal getMultiple3() {
        return multiple3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.multiple3
     *
     * @param multiple3 the value for stat_dic_times.multiple3
     *
     * @mbg.generated
     */
    public void setMultiple3(BigDecimal multiple3) {
        this.multiple3 = multiple3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_dic_times.multiple4
     *
     * @return the value of stat_dic_times.multiple4
     *
     * @mbg.generated
     */
    public BigDecimal getMultiple4() {
        return multiple4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_dic_times.multiple4
     *
     * @param multiple4 the value for stat_dic_times.multiple4
     *
     * @mbg.generated
     */
    public void setMultiple4(BigDecimal multiple4) {
        this.multiple4 = multiple4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_dic_times
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", depCode=").append(depCode);
        sb.append(", dicCode=").append(dicCode);
        sb.append(", dicName=").append(dicName);
        sb.append(", statrTime1Type=").append(statrTime1Type);
        sb.append(", startTime1Class=").append(startTime1Class);
        sb.append(", startTime1=").append(startTime1);
        sb.append(", endTime1Type=").append(endTime1Type);
        sb.append(", endTime1Class=").append(endTime1Class);
        sb.append(", endTime1=").append(endTime1);
        sb.append(", statrTime2Type=").append(statrTime2Type);
        sb.append(", startTime2Class=").append(startTime2Class);
        sb.append(", startTime2=").append(startTime2);
        sb.append(", endTime2Type=").append(endTime2Type);
        sb.append(", endTime2Class=").append(endTime2Class);
        sb.append(", endTime2=").append(endTime2);
        sb.append(", startTime3Class=").append(startTime3Class);
        sb.append(", statrTime3Type=").append(statrTime3Type);
        sb.append(", startTime3=").append(startTime3);
        sb.append(", endTime3Type=").append(endTime3Type);
        sb.append(", endTime3Class=").append(endTime3Class);
        sb.append(", endTime3=").append(endTime3);
        sb.append(", dicExplain=").append(dicExplain);
        sb.append(", dicType=").append(dicType);
        sb.append(", dicSort=").append(dicSort);
        sb.append(", state=").append(state);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", multiple1=").append(multiple1);
        sb.append(", multiple2=").append(multiple2);
        sb.append(", multiple3=").append(multiple3);
        sb.append(", multiple4=").append(multiple4);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}