package com.dao.entity.zjsouredata;

import java.io.Serializable;

public class BaseSearchModules implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.modules_Id
     *
     * @mbg.generated
     */
    private String modulesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.modules_name
     *
     * @mbg.generated
     */
    private String modulesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.pojo_class
     *
     * @mbg.generated
     */
    private String pojoClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.remark1
     *
     * @mbg.generated
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.remark2
     *
     * @mbg.generated
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_search_modules.dep_code
     *
     * @mbg.generated
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_search_modules
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.id
     *
     * @return the value of base_search_modules.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.id
     *
     * @param id the value for base_search_modules.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.modules_Id
     *
     * @return the value of base_search_modules.modules_Id
     *
     * @mbg.generated
     */
    public String getModulesId() {
        return modulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.modules_Id
     *
     * @param modulesId the value for base_search_modules.modules_Id
     *
     * @mbg.generated
     */
    public void setModulesId(String modulesId) {
        this.modulesId = modulesId == null ? null : modulesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.modules_name
     *
     * @return the value of base_search_modules.modules_name
     *
     * @mbg.generated
     */
    public String getModulesName() {
        return modulesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.modules_name
     *
     * @param modulesName the value for base_search_modules.modules_name
     *
     * @mbg.generated
     */
    public void setModulesName(String modulesName) {
        this.modulesName = modulesName == null ? null : modulesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.pojo_class
     *
     * @return the value of base_search_modules.pojo_class
     *
     * @mbg.generated
     */
    public String getPojoClass() {
        return pojoClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.pojo_class
     *
     * @param pojoClass the value for base_search_modules.pojo_class
     *
     * @mbg.generated
     */
    public void setPojoClass(String pojoClass) {
        this.pojoClass = pojoClass == null ? null : pojoClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.remark1
     *
     * @return the value of base_search_modules.remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.remark1
     *
     * @param remark1 the value for base_search_modules.remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.remark2
     *
     * @return the value of base_search_modules.remark2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.remark2
     *
     * @param remark2 the value for base_search_modules.remark2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_search_modules.dep_code
     *
     * @return the value of base_search_modules.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_search_modules.dep_code
     *
     * @param depCode the value for base_search_modules.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_search_modules
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", modulesId=").append(modulesId);
        sb.append(", modulesName=").append(modulesName);
        sb.append(", pojoClass=").append(pojoClass);
        sb.append(", remark1=").append(remark1);
        sb.append(", remark2=").append(remark2);
        sb.append(", depCode=").append(depCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}