package com.dao.entity.zjsouredata;

import com.dao.entity.sys.ComColumn;

import java.io.Serializable;
import java.util.Date;

public class DwdRkZfba2XyrxxDd extends ComColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.rybh
     *
     * @mbg.generated
     */
    private String rybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfzbxm
     *
     * @mbg.generated
     */
    private String sfzbxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.ryxm
     *
     * @mbg.generated
     */
    private String ryxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.xbdm
     *
     * @mbg.generated
     */
    private String xbdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.xb
     *
     * @mbg.generated
     */
    private String xb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.csrq
     *
     * @mbg.generated
     */
    private String csrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.csrq_dt
     *
     * @mbg.generated
     */
    private Date csrqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.csrq_int
     *
     * @mbg.generated
     */
    private Integer csrqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.ry_sfzh
     *
     * @mbg.generated
     */
    private String rySfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zjlxdm
     *
     * @mbg.generated
     */
    private String zjlxdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zjlx
     *
     * @mbg.generated
     */
    private String zjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zjhm
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.mzdm
     *
     * @mbg.generated
     */
    private String mzdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.mz
     *
     * @mbg.generated
     */
    private String mz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.gj
     *
     * @mbg.generated
     */
    private String gj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.cym
     *
     * @mbg.generated
     */
    private String cym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.bm
     *
     * @mbg.generated
     */
    private String bm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.ch
     *
     * @mbg.generated
     */
    private String ch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.rysfdm
     *
     * @mbg.generated
     */
    private String rysfdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.rysf
     *
     * @mbg.generated
     */
    private String rysf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfsfbm
     *
     * @mbg.generated
     */
    private String sfsfbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.whcddm
     *
     * @mbg.generated
     */
    private String whcddm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.whcd
     *
     * @mbg.generated
     */
    private String whcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zzmmdm
     *
     * @mbg.generated
     */
    private String zzmmdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zzmm
     *
     * @mbg.generated
     */
    private String zzmm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.hyzkdm
     *
     * @mbg.generated
     */
    private String hyzkdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.hyzk
     *
     * @mbg.generated
     */
    private String hyzk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lxfs
     *
     * @mbg.generated
     */
    private String lxfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.gzdw
     *
     * @mbg.generated
     */
    private String gzdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.hjd_xzqh
     *
     * @mbg.generated
     */
    private String hjdXzqh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.hjdxz
     *
     * @mbg.generated
     */
    private String hjdxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.xzd_xzqh
     *
     * @mbg.generated
     */
    private String xzdXzqh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.xzdxz
     *
     * @mbg.generated
     */
    private String xzdxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.ry_zaymc
     *
     * @mbg.generated
     */
    private String ryZaymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.ry_zaybh
     *
     * @mbg.generated
     */
    private String ryZaybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfzt
     *
     * @mbg.generated
     */
    private String sfzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sftsqt
     *
     * @mbg.generated
     */
    private String sftsqt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.qkqk
     *
     * @mbg.generated
     */
    private String qkqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.jtzk
     *
     * @mbg.generated
     */
    private String jtzk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.shgx
     *
     * @mbg.generated
     */
    private String shgx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.crj_zjlx
     *
     * @mbg.generated
     */
    private String crjZjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.crj_zjhm
     *
     * @mbg.generated
     */
    private String crjZjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zpid
     *
     * @mbg.generated
     */
    private String zpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfjrbaq
     *
     * @mbg.generated
     */
    private String sfjrbaq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfythcj
     *
     * @mbg.generated
     */
    private String sfythcj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfwfxyr
     *
     * @mbg.generated
     */
    private String sfwfxyr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sffzxyr
     *
     * @mbg.generated
     */
    private String sffzxyr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sflary
     *
     * @mbg.generated
     */
    private String sflary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lrdw_bh
     *
     * @mbg.generated
     */
    private String lrdwBh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lrdw_xtbh
     *
     * @mbg.generated
     */
    private String lrdwXtbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lrsj
     *
     * @mbg.generated
     */
    private String lrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lrsj_dt
     *
     * @mbg.generated
     */
    private Date lrsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lrsj_int
     *
     * @mbg.generated
     */
    private Integer lrsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.lrr_sfzh
     *
     * @mbg.generated
     */
    private String lrrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj
     *
     * @mbg.generated
     */
    private String tjxgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj_dt
     *
     * @mbg.generated
     */
    private Date tjxgsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj_int
     *
     * @mbg.generated
     */
    private Integer tjxgsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.tjxgr_sfzh
     *
     * @mbg.generated
     */
    private String tjxgrSfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.isdel
     *
     * @mbg.generated
     */
    private String isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.data_flag
     *
     * @mbg.generated
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.baq_rybh
     *
     * @mbg.generated
     */
    private String baqRybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfwcn
     *
     * @mbg.generated
     */
    private String sfwcn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.zanl
     *
     * @mbg.generated
     */
    private String zanl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.sfda
     *
     * @mbg.generated
     */
    private String sfda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.op_type
     *
     * @mbg.generated
     */
    private String opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.dwd_yxbz
     *
     * @mbg.generated
     */
    private String dwdYxbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.dwd_zjid
     *
     * @mbg.generated
     */
    private String dwdZjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.time_stamp
     *
     * @mbg.generated
     */
    private String timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.gmsfhm
     *
     * @mbg.generated
     */
    private String gmsfhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.dwd_zjhm
     *
     * @mbg.generated
     */
    private String dwdZjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.dwd_loadtime
     *
     * @mbg.generated
     */
    private String dwdLoadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.dwd_upDateTime
     *
     * @mbg.generated
     */
    private String dwdUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_rk_zfba2_xyrxx_dd.dep_code
     *
     * @mbg.generated
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwd_rk_zfba2_xyrxx_dd
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.id
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.id
     *
     * @param id the value for dwd_rk_zfba2_xyrxx_dd.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.rybh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.rybh
     *
     * @mbg.generated
     */
    public String getRybh() {
        return rybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.rybh
     *
     * @param rybh the value for dwd_rk_zfba2_xyrxx_dd.rybh
     *
     * @mbg.generated
     */
    public void setRybh(String rybh) {
        this.rybh = rybh == null ? null : rybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfzbxm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfzbxm
     *
     * @mbg.generated
     */
    public String getSfzbxm() {
        return sfzbxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfzbxm
     *
     * @param sfzbxm the value for dwd_rk_zfba2_xyrxx_dd.sfzbxm
     *
     * @mbg.generated
     */
    public void setSfzbxm(String sfzbxm) {
        this.sfzbxm = sfzbxm == null ? null : sfzbxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.ryxm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.ryxm
     *
     * @mbg.generated
     */
    public String getRyxm() {
        return ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.ryxm
     *
     * @param ryxm the value for dwd_rk_zfba2_xyrxx_dd.ryxm
     *
     * @mbg.generated
     */
    public void setRyxm(String ryxm) {
        this.ryxm = ryxm == null ? null : ryxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.xbdm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.xbdm
     *
     * @mbg.generated
     */
    public String getXbdm() {
        return xbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.xbdm
     *
     * @param xbdm the value for dwd_rk_zfba2_xyrxx_dd.xbdm
     *
     * @mbg.generated
     */
    public void setXbdm(String xbdm) {
        this.xbdm = xbdm == null ? null : xbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.xb
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.xb
     *
     * @mbg.generated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.xb
     *
     * @param xb the value for dwd_rk_zfba2_xyrxx_dd.xb
     *
     * @mbg.generated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.csrq
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.csrq
     *
     * @mbg.generated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.csrq
     *
     * @param csrq the value for dwd_rk_zfba2_xyrxx_dd.csrq
     *
     * @mbg.generated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.csrq_dt
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.csrq_dt
     *
     * @mbg.generated
     */
    public Date getCsrqDt() {
        return csrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.csrq_dt
     *
     * @param csrqDt the value for dwd_rk_zfba2_xyrxx_dd.csrq_dt
     *
     * @mbg.generated
     */
    public void setCsrqDt(Date csrqDt) {
        this.csrqDt = csrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.csrq_int
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.csrq_int
     *
     * @mbg.generated
     */
    public Integer getCsrqInt() {
        return csrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.csrq_int
     *
     * @param csrqInt the value for dwd_rk_zfba2_xyrxx_dd.csrq_int
     *
     * @mbg.generated
     */
    public void setCsrqInt(Integer csrqInt) {
        this.csrqInt = csrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.ry_sfzh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.ry_sfzh
     *
     * @mbg.generated
     */
    public String getRySfzh() {
        return rySfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.ry_sfzh
     *
     * @param rySfzh the value for dwd_rk_zfba2_xyrxx_dd.ry_sfzh
     *
     * @mbg.generated
     */
    public void setRySfzh(String rySfzh) {
        this.rySfzh = rySfzh == null ? null : rySfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zjlxdm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zjlxdm
     *
     * @mbg.generated
     */
    public String getZjlxdm() {
        return zjlxdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zjlxdm
     *
     * @param zjlxdm the value for dwd_rk_zfba2_xyrxx_dd.zjlxdm
     *
     * @mbg.generated
     */
    public void setZjlxdm(String zjlxdm) {
        this.zjlxdm = zjlxdm == null ? null : zjlxdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zjlx
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zjlx
     *
     * @mbg.generated
     */
    public String getZjlx() {
        return zjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zjlx
     *
     * @param zjlx the value for dwd_rk_zfba2_xyrxx_dd.zjlx
     *
     * @mbg.generated
     */
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx == null ? null : zjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zjhm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zjhm
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zjhm
     *
     * @param zjhm the value for dwd_rk_zfba2_xyrxx_dd.zjhm
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.mzdm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.mzdm
     *
     * @mbg.generated
     */
    public String getMzdm() {
        return mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.mzdm
     *
     * @param mzdm the value for dwd_rk_zfba2_xyrxx_dd.mzdm
     *
     * @mbg.generated
     */
    public void setMzdm(String mzdm) {
        this.mzdm = mzdm == null ? null : mzdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.mz
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.mz
     *
     * @mbg.generated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.mz
     *
     * @param mz the value for dwd_rk_zfba2_xyrxx_dd.mz
     *
     * @mbg.generated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.gj
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.gj
     *
     * @mbg.generated
     */
    public String getGj() {
        return gj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.gj
     *
     * @param gj the value for dwd_rk_zfba2_xyrxx_dd.gj
     *
     * @mbg.generated
     */
    public void setGj(String gj) {
        this.gj = gj == null ? null : gj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.cym
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.cym
     *
     * @mbg.generated
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.cym
     *
     * @param cym the value for dwd_rk_zfba2_xyrxx_dd.cym
     *
     * @mbg.generated
     */
    public void setCym(String cym) {
        this.cym = cym == null ? null : cym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.bm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.bm
     *
     * @mbg.generated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.bm
     *
     * @param bm the value for dwd_rk_zfba2_xyrxx_dd.bm
     *
     * @mbg.generated
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.ch
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.ch
     *
     * @mbg.generated
     */
    public String getCh() {
        return ch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.ch
     *
     * @param ch the value for dwd_rk_zfba2_xyrxx_dd.ch
     *
     * @mbg.generated
     */
    public void setCh(String ch) {
        this.ch = ch == null ? null : ch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.rysfdm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.rysfdm
     *
     * @mbg.generated
     */
    public String getRysfdm() {
        return rysfdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.rysfdm
     *
     * @param rysfdm the value for dwd_rk_zfba2_xyrxx_dd.rysfdm
     *
     * @mbg.generated
     */
    public void setRysfdm(String rysfdm) {
        this.rysfdm = rysfdm == null ? null : rysfdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.rysf
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.rysf
     *
     * @mbg.generated
     */
    public String getRysf() {
        return rysf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.rysf
     *
     * @param rysf the value for dwd_rk_zfba2_xyrxx_dd.rysf
     *
     * @mbg.generated
     */
    public void setRysf(String rysf) {
        this.rysf = rysf == null ? null : rysf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfsfbm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfsfbm
     *
     * @mbg.generated
     */
    public String getSfsfbm() {
        return sfsfbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfsfbm
     *
     * @param sfsfbm the value for dwd_rk_zfba2_xyrxx_dd.sfsfbm
     *
     * @mbg.generated
     */
    public void setSfsfbm(String sfsfbm) {
        this.sfsfbm = sfsfbm == null ? null : sfsfbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.whcddm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.whcddm
     *
     * @mbg.generated
     */
    public String getWhcddm() {
        return whcddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.whcddm
     *
     * @param whcddm the value for dwd_rk_zfba2_xyrxx_dd.whcddm
     *
     * @mbg.generated
     */
    public void setWhcddm(String whcddm) {
        this.whcddm = whcddm == null ? null : whcddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.whcd
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.whcd
     *
     * @mbg.generated
     */
    public String getWhcd() {
        return whcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.whcd
     *
     * @param whcd the value for dwd_rk_zfba2_xyrxx_dd.whcd
     *
     * @mbg.generated
     */
    public void setWhcd(String whcd) {
        this.whcd = whcd == null ? null : whcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zzmmdm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zzmmdm
     *
     * @mbg.generated
     */
    public String getZzmmdm() {
        return zzmmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zzmmdm
     *
     * @param zzmmdm the value for dwd_rk_zfba2_xyrxx_dd.zzmmdm
     *
     * @mbg.generated
     */
    public void setZzmmdm(String zzmmdm) {
        this.zzmmdm = zzmmdm == null ? null : zzmmdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zzmm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zzmm
     *
     * @mbg.generated
     */
    public String getZzmm() {
        return zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zzmm
     *
     * @param zzmm the value for dwd_rk_zfba2_xyrxx_dd.zzmm
     *
     * @mbg.generated
     */
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm == null ? null : zzmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.hyzkdm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.hyzkdm
     *
     * @mbg.generated
     */
    public String getHyzkdm() {
        return hyzkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.hyzkdm
     *
     * @param hyzkdm the value for dwd_rk_zfba2_xyrxx_dd.hyzkdm
     *
     * @mbg.generated
     */
    public void setHyzkdm(String hyzkdm) {
        this.hyzkdm = hyzkdm == null ? null : hyzkdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.hyzk
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.hyzk
     *
     * @mbg.generated
     */
    public String getHyzk() {
        return hyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.hyzk
     *
     * @param hyzk the value for dwd_rk_zfba2_xyrxx_dd.hyzk
     *
     * @mbg.generated
     */
    public void setHyzk(String hyzk) {
        this.hyzk = hyzk == null ? null : hyzk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lxfs
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lxfs
     *
     * @mbg.generated
     */
    public String getLxfs() {
        return lxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lxfs
     *
     * @param lxfs the value for dwd_rk_zfba2_xyrxx_dd.lxfs
     *
     * @mbg.generated
     */
    public void setLxfs(String lxfs) {
        this.lxfs = lxfs == null ? null : lxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.gzdw
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.gzdw
     *
     * @mbg.generated
     */
    public String getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.gzdw
     *
     * @param gzdw the value for dwd_rk_zfba2_xyrxx_dd.gzdw
     *
     * @mbg.generated
     */
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw == null ? null : gzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.hjd_xzqh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.hjd_xzqh
     *
     * @mbg.generated
     */
    public String getHjdXzqh() {
        return hjdXzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.hjd_xzqh
     *
     * @param hjdXzqh the value for dwd_rk_zfba2_xyrxx_dd.hjd_xzqh
     *
     * @mbg.generated
     */
    public void setHjdXzqh(String hjdXzqh) {
        this.hjdXzqh = hjdXzqh == null ? null : hjdXzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.hjdxz
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.hjdxz
     *
     * @mbg.generated
     */
    public String getHjdxz() {
        return hjdxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.hjdxz
     *
     * @param hjdxz the value for dwd_rk_zfba2_xyrxx_dd.hjdxz
     *
     * @mbg.generated
     */
    public void setHjdxz(String hjdxz) {
        this.hjdxz = hjdxz == null ? null : hjdxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.xzd_xzqh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.xzd_xzqh
     *
     * @mbg.generated
     */
    public String getXzdXzqh() {
        return xzdXzqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.xzd_xzqh
     *
     * @param xzdXzqh the value for dwd_rk_zfba2_xyrxx_dd.xzd_xzqh
     *
     * @mbg.generated
     */
    public void setXzdXzqh(String xzdXzqh) {
        this.xzdXzqh = xzdXzqh == null ? null : xzdXzqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.xzdxz
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.xzdxz
     *
     * @mbg.generated
     */
    public String getXzdxz() {
        return xzdxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.xzdxz
     *
     * @param xzdxz the value for dwd_rk_zfba2_xyrxx_dd.xzdxz
     *
     * @mbg.generated
     */
    public void setXzdxz(String xzdxz) {
        this.xzdxz = xzdxz == null ? null : xzdxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.ry_zaymc
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.ry_zaymc
     *
     * @mbg.generated
     */
    public String getRyZaymc() {
        return ryZaymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.ry_zaymc
     *
     * @param ryZaymc the value for dwd_rk_zfba2_xyrxx_dd.ry_zaymc
     *
     * @mbg.generated
     */
    public void setRyZaymc(String ryZaymc) {
        this.ryZaymc = ryZaymc == null ? null : ryZaymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.ry_zaybh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.ry_zaybh
     *
     * @mbg.generated
     */
    public String getRyZaybh() {
        return ryZaybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.ry_zaybh
     *
     * @param ryZaybh the value for dwd_rk_zfba2_xyrxx_dd.ry_zaybh
     *
     * @mbg.generated
     */
    public void setRyZaybh(String ryZaybh) {
        this.ryZaybh = ryZaybh == null ? null : ryZaybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfzt
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfzt
     *
     * @mbg.generated
     */
    public String getSfzt() {
        return sfzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfzt
     *
     * @param sfzt the value for dwd_rk_zfba2_xyrxx_dd.sfzt
     *
     * @mbg.generated
     */
    public void setSfzt(String sfzt) {
        this.sfzt = sfzt == null ? null : sfzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sftsqt
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sftsqt
     *
     * @mbg.generated
     */
    public String getSftsqt() {
        return sftsqt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sftsqt
     *
     * @param sftsqt the value for dwd_rk_zfba2_xyrxx_dd.sftsqt
     *
     * @mbg.generated
     */
    public void setSftsqt(String sftsqt) {
        this.sftsqt = sftsqt == null ? null : sftsqt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.qkqk
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.qkqk
     *
     * @mbg.generated
     */
    public String getQkqk() {
        return qkqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.qkqk
     *
     * @param qkqk the value for dwd_rk_zfba2_xyrxx_dd.qkqk
     *
     * @mbg.generated
     */
    public void setQkqk(String qkqk) {
        this.qkqk = qkqk == null ? null : qkqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.jtzk
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.jtzk
     *
     * @mbg.generated
     */
    public String getJtzk() {
        return jtzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.jtzk
     *
     * @param jtzk the value for dwd_rk_zfba2_xyrxx_dd.jtzk
     *
     * @mbg.generated
     */
    public void setJtzk(String jtzk) {
        this.jtzk = jtzk == null ? null : jtzk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.shgx
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.shgx
     *
     * @mbg.generated
     */
    public String getShgx() {
        return shgx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.shgx
     *
     * @param shgx the value for dwd_rk_zfba2_xyrxx_dd.shgx
     *
     * @mbg.generated
     */
    public void setShgx(String shgx) {
        this.shgx = shgx == null ? null : shgx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.crj_zjlx
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.crj_zjlx
     *
     * @mbg.generated
     */
    public String getCrjZjlx() {
        return crjZjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.crj_zjlx
     *
     * @param crjZjlx the value for dwd_rk_zfba2_xyrxx_dd.crj_zjlx
     *
     * @mbg.generated
     */
    public void setCrjZjlx(String crjZjlx) {
        this.crjZjlx = crjZjlx == null ? null : crjZjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.crj_zjhm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.crj_zjhm
     *
     * @mbg.generated
     */
    public String getCrjZjhm() {
        return crjZjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.crj_zjhm
     *
     * @param crjZjhm the value for dwd_rk_zfba2_xyrxx_dd.crj_zjhm
     *
     * @mbg.generated
     */
    public void setCrjZjhm(String crjZjhm) {
        this.crjZjhm = crjZjhm == null ? null : crjZjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zpid
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zpid
     *
     * @mbg.generated
     */
    public String getZpid() {
        return zpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zpid
     *
     * @param zpid the value for dwd_rk_zfba2_xyrxx_dd.zpid
     *
     * @mbg.generated
     */
    public void setZpid(String zpid) {
        this.zpid = zpid == null ? null : zpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfjrbaq
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfjrbaq
     *
     * @mbg.generated
     */
    public String getSfjrbaq() {
        return sfjrbaq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfjrbaq
     *
     * @param sfjrbaq the value for dwd_rk_zfba2_xyrxx_dd.sfjrbaq
     *
     * @mbg.generated
     */
    public void setSfjrbaq(String sfjrbaq) {
        this.sfjrbaq = sfjrbaq == null ? null : sfjrbaq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfythcj
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfythcj
     *
     * @mbg.generated
     */
    public String getSfythcj() {
        return sfythcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfythcj
     *
     * @param sfythcj the value for dwd_rk_zfba2_xyrxx_dd.sfythcj
     *
     * @mbg.generated
     */
    public void setSfythcj(String sfythcj) {
        this.sfythcj = sfythcj == null ? null : sfythcj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfwfxyr
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfwfxyr
     *
     * @mbg.generated
     */
    public String getSfwfxyr() {
        return sfwfxyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfwfxyr
     *
     * @param sfwfxyr the value for dwd_rk_zfba2_xyrxx_dd.sfwfxyr
     *
     * @mbg.generated
     */
    public void setSfwfxyr(String sfwfxyr) {
        this.sfwfxyr = sfwfxyr == null ? null : sfwfxyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sffzxyr
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sffzxyr
     *
     * @mbg.generated
     */
    public String getSffzxyr() {
        return sffzxyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sffzxyr
     *
     * @param sffzxyr the value for dwd_rk_zfba2_xyrxx_dd.sffzxyr
     *
     * @mbg.generated
     */
    public void setSffzxyr(String sffzxyr) {
        this.sffzxyr = sffzxyr == null ? null : sffzxyr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sflary
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sflary
     *
     * @mbg.generated
     */
    public String getSflary() {
        return sflary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sflary
     *
     * @param sflary the value for dwd_rk_zfba2_xyrxx_dd.sflary
     *
     * @mbg.generated
     */
    public void setSflary(String sflary) {
        this.sflary = sflary == null ? null : sflary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lrdw_bh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lrdw_bh
     *
     * @mbg.generated
     */
    public String getLrdwBh() {
        return lrdwBh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lrdw_bh
     *
     * @param lrdwBh the value for dwd_rk_zfba2_xyrxx_dd.lrdw_bh
     *
     * @mbg.generated
     */
    public void setLrdwBh(String lrdwBh) {
        this.lrdwBh = lrdwBh == null ? null : lrdwBh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lrdw_xtbh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lrdw_xtbh
     *
     * @mbg.generated
     */
    public String getLrdwXtbh() {
        return lrdwXtbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lrdw_xtbh
     *
     * @param lrdwXtbh the value for dwd_rk_zfba2_xyrxx_dd.lrdw_xtbh
     *
     * @mbg.generated
     */
    public void setLrdwXtbh(String lrdwXtbh) {
        this.lrdwXtbh = lrdwXtbh == null ? null : lrdwXtbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lrsj
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lrsj
     *
     * @mbg.generated
     */
    public String getLrsj() {
        return lrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lrsj
     *
     * @param lrsj the value for dwd_rk_zfba2_xyrxx_dd.lrsj
     *
     * @mbg.generated
     */
    public void setLrsj(String lrsj) {
        this.lrsj = lrsj == null ? null : lrsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lrsj_dt
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lrsj_dt
     *
     * @mbg.generated
     */
    public Date getLrsjDt() {
        return lrsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lrsj_dt
     *
     * @param lrsjDt the value for dwd_rk_zfba2_xyrxx_dd.lrsj_dt
     *
     * @mbg.generated
     */
    public void setLrsjDt(Date lrsjDt) {
        this.lrsjDt = lrsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lrsj_int
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lrsj_int
     *
     * @mbg.generated
     */
    public Integer getLrsjInt() {
        return lrsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lrsj_int
     *
     * @param lrsjInt the value for dwd_rk_zfba2_xyrxx_dd.lrsj_int
     *
     * @mbg.generated
     */
    public void setLrsjInt(Integer lrsjInt) {
        this.lrsjInt = lrsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.lrr_sfzh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.lrr_sfzh
     *
     * @mbg.generated
     */
    public String getLrrSfzh() {
        return lrrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.lrr_sfzh
     *
     * @param lrrSfzh the value for dwd_rk_zfba2_xyrxx_dd.lrr_sfzh
     *
     * @mbg.generated
     */
    public void setLrrSfzh(String lrrSfzh) {
        this.lrrSfzh = lrrSfzh == null ? null : lrrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.tjxgsj
     *
     * @mbg.generated
     */
    public String getTjxgsj() {
        return tjxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj
     *
     * @param tjxgsj the value for dwd_rk_zfba2_xyrxx_dd.tjxgsj
     *
     * @mbg.generated
     */
    public void setTjxgsj(String tjxgsj) {
        this.tjxgsj = tjxgsj == null ? null : tjxgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj_dt
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.tjxgsj_dt
     *
     * @mbg.generated
     */
    public Date getTjxgsjDt() {
        return tjxgsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj_dt
     *
     * @param tjxgsjDt the value for dwd_rk_zfba2_xyrxx_dd.tjxgsj_dt
     *
     * @mbg.generated
     */
    public void setTjxgsjDt(Date tjxgsjDt) {
        this.tjxgsjDt = tjxgsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj_int
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.tjxgsj_int
     *
     * @mbg.generated
     */
    public Integer getTjxgsjInt() {
        return tjxgsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgsj_int
     *
     * @param tjxgsjInt the value for dwd_rk_zfba2_xyrxx_dd.tjxgsj_int
     *
     * @mbg.generated
     */
    public void setTjxgsjInt(Integer tjxgsjInt) {
        this.tjxgsjInt = tjxgsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgr_sfzh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.tjxgr_sfzh
     *
     * @mbg.generated
     */
    public String getTjxgrSfzh() {
        return tjxgrSfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.tjxgr_sfzh
     *
     * @param tjxgrSfzh the value for dwd_rk_zfba2_xyrxx_dd.tjxgr_sfzh
     *
     * @mbg.generated
     */
    public void setTjxgrSfzh(String tjxgrSfzh) {
        this.tjxgrSfzh = tjxgrSfzh == null ? null : tjxgrSfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.isdel
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.isdel
     *
     * @mbg.generated
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.isdel
     *
     * @param isdel the value for dwd_rk_zfba2_xyrxx_dd.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel == null ? null : isdel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.data_flag
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.data_flag
     *
     * @mbg.generated
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.data_flag
     *
     * @param dataFlag the value for dwd_rk_zfba2_xyrxx_dd.data_flag
     *
     * @mbg.generated
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.baq_rybh
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.baq_rybh
     *
     * @mbg.generated
     */
    public String getBaqRybh() {
        return baqRybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.baq_rybh
     *
     * @param baqRybh the value for dwd_rk_zfba2_xyrxx_dd.baq_rybh
     *
     * @mbg.generated
     */
    public void setBaqRybh(String baqRybh) {
        this.baqRybh = baqRybh == null ? null : baqRybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.age
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.age
     *
     * @mbg.generated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.age
     *
     * @param age the value for dwd_rk_zfba2_xyrxx_dd.age
     *
     * @mbg.generated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfwcn
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfwcn
     *
     * @mbg.generated
     */
    public String getSfwcn() {
        return sfwcn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfwcn
     *
     * @param sfwcn the value for dwd_rk_zfba2_xyrxx_dd.sfwcn
     *
     * @mbg.generated
     */
    public void setSfwcn(String sfwcn) {
        this.sfwcn = sfwcn == null ? null : sfwcn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.zanl
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.zanl
     *
     * @mbg.generated
     */
    public String getZanl() {
        return zanl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.zanl
     *
     * @param zanl the value for dwd_rk_zfba2_xyrxx_dd.zanl
     *
     * @mbg.generated
     */
    public void setZanl(String zanl) {
        this.zanl = zanl == null ? null : zanl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.sfda
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.sfda
     *
     * @mbg.generated
     */
    public String getSfda() {
        return sfda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.sfda
     *
     * @param sfda the value for dwd_rk_zfba2_xyrxx_dd.sfda
     *
     * @mbg.generated
     */
    public void setSfda(String sfda) {
        this.sfda = sfda == null ? null : sfda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.op_type
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.op_type
     *
     * @mbg.generated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.op_type
     *
     * @param opType the value for dwd_rk_zfba2_xyrxx_dd.op_type
     *
     * @mbg.generated
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_yxbz
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.dwd_yxbz
     *
     * @mbg.generated
     */
    public String getDwdYxbz() {
        return dwdYxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_yxbz
     *
     * @param dwdYxbz the value for dwd_rk_zfba2_xyrxx_dd.dwd_yxbz
     *
     * @mbg.generated
     */
    public void setDwdYxbz(String dwdYxbz) {
        this.dwdYxbz = dwdYxbz == null ? null : dwdYxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_zjid
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.dwd_zjid
     *
     * @mbg.generated
     */
    public String getDwdZjid() {
        return dwdZjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_zjid
     *
     * @param dwdZjid the value for dwd_rk_zfba2_xyrxx_dd.dwd_zjid
     *
     * @mbg.generated
     */
    public void setDwdZjid(String dwdZjid) {
        this.dwdZjid = dwdZjid == null ? null : dwdZjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.time_stamp
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.time_stamp
     *
     * @mbg.generated
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.time_stamp
     *
     * @param timeStamp the value for dwd_rk_zfba2_xyrxx_dd.time_stamp
     *
     * @mbg.generated
     */
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp == null ? null : timeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.gmsfhm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.gmsfhm
     *
     * @mbg.generated
     */
    public String getGmsfhm() {
        return gmsfhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.gmsfhm
     *
     * @param gmsfhm the value for dwd_rk_zfba2_xyrxx_dd.gmsfhm
     *
     * @mbg.generated
     */
    public void setGmsfhm(String gmsfhm) {
        this.gmsfhm = gmsfhm == null ? null : gmsfhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_zjhm
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.dwd_zjhm
     *
     * @mbg.generated
     */
    public String getDwdZjhm() {
        return dwdZjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_zjhm
     *
     * @param dwdZjhm the value for dwd_rk_zfba2_xyrxx_dd.dwd_zjhm
     *
     * @mbg.generated
     */
    public void setDwdZjhm(String dwdZjhm) {
        this.dwdZjhm = dwdZjhm == null ? null : dwdZjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_loadtime
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.dwd_loadtime
     *
     * @mbg.generated
     */
    public String getDwdLoadtime() {
        return dwdLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_loadtime
     *
     * @param dwdLoadtime the value for dwd_rk_zfba2_xyrxx_dd.dwd_loadtime
     *
     * @mbg.generated
     */
    public void setDwdLoadtime(String dwdLoadtime) {
        this.dwdLoadtime = dwdLoadtime == null ? null : dwdLoadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_upDateTime
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.dwd_upDateTime
     *
     * @mbg.generated
     */
    public String getDwdUpdatetime() {
        return dwdUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.dwd_upDateTime
     *
     * @param dwdUpdatetime the value for dwd_rk_zfba2_xyrxx_dd.dwd_upDateTime
     *
     * @mbg.generated
     */
    public void setDwdUpdatetime(String dwdUpdatetime) {
        this.dwdUpdatetime = dwdUpdatetime == null ? null : dwdUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_rk_zfba2_xyrxx_dd.dep_code
     *
     * @return the value of dwd_rk_zfba2_xyrxx_dd.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_rk_zfba2_xyrxx_dd.dep_code
     *
     * @param depCode the value for dwd_rk_zfba2_xyrxx_dd.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_rk_zfba2_xyrxx_dd
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rybh=").append(rybh);
        sb.append(", sfzbxm=").append(sfzbxm);
        sb.append(", ryxm=").append(ryxm);
        sb.append(", xbdm=").append(xbdm);
        sb.append(", xb=").append(xb);
        sb.append(", csrq=").append(csrq);
        sb.append(", csrqDt=").append(csrqDt);
        sb.append(", csrqInt=").append(csrqInt);
        sb.append(", rySfzh=").append(rySfzh);
        sb.append(", zjlxdm=").append(zjlxdm);
        sb.append(", zjlx=").append(zjlx);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", mzdm=").append(mzdm);
        sb.append(", mz=").append(mz);
        sb.append(", gj=").append(gj);
        sb.append(", cym=").append(cym);
        sb.append(", bm=").append(bm);
        sb.append(", ch=").append(ch);
        sb.append(", rysfdm=").append(rysfdm);
        sb.append(", rysf=").append(rysf);
        sb.append(", sfsfbm=").append(sfsfbm);
        sb.append(", whcddm=").append(whcddm);
        sb.append(", whcd=").append(whcd);
        sb.append(", zzmmdm=").append(zzmmdm);
        sb.append(", zzmm=").append(zzmm);
        sb.append(", hyzkdm=").append(hyzkdm);
        sb.append(", hyzk=").append(hyzk);
        sb.append(", lxfs=").append(lxfs);
        sb.append(", gzdw=").append(gzdw);
        sb.append(", hjdXzqh=").append(hjdXzqh);
        sb.append(", hjdxz=").append(hjdxz);
        sb.append(", xzdXzqh=").append(xzdXzqh);
        sb.append(", xzdxz=").append(xzdxz);
        sb.append(", ryZaymc=").append(ryZaymc);
        sb.append(", ryZaybh=").append(ryZaybh);
        sb.append(", sfzt=").append(sfzt);
        sb.append(", sftsqt=").append(sftsqt);
        sb.append(", qkqk=").append(qkqk);
        sb.append(", jtzk=").append(jtzk);
        sb.append(", shgx=").append(shgx);
        sb.append(", crjZjlx=").append(crjZjlx);
        sb.append(", crjZjhm=").append(crjZjhm);
        sb.append(", zpid=").append(zpid);
        sb.append(", sfjrbaq=").append(sfjrbaq);
        sb.append(", sfythcj=").append(sfythcj);
        sb.append(", sfwfxyr=").append(sfwfxyr);
        sb.append(", sffzxyr=").append(sffzxyr);
        sb.append(", sflary=").append(sflary);
        sb.append(", lrdwBh=").append(lrdwBh);
        sb.append(", lrdwXtbh=").append(lrdwXtbh);
        sb.append(", lrsj=").append(lrsj);
        sb.append(", lrsjDt=").append(lrsjDt);
        sb.append(", lrsjInt=").append(lrsjInt);
        sb.append(", lrrSfzh=").append(lrrSfzh);
        sb.append(", tjxgsj=").append(tjxgsj);
        sb.append(", tjxgsjDt=").append(tjxgsjDt);
        sb.append(", tjxgsjInt=").append(tjxgsjInt);
        sb.append(", tjxgrSfzh=").append(tjxgrSfzh);
        sb.append(", isdel=").append(isdel);
        sb.append(", dataFlag=").append(dataFlag);
        sb.append(", baqRybh=").append(baqRybh);
        sb.append(", age=").append(age);
        sb.append(", sfwcn=").append(sfwcn);
        sb.append(", zanl=").append(zanl);
        sb.append(", sfda=").append(sfda);
        sb.append(", opType=").append(opType);
        sb.append(", dwdYxbz=").append(dwdYxbz);
        sb.append(", dwdZjid=").append(dwdZjid);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", gmsfhm=").append(gmsfhm);
        sb.append(", dwdZjhm=").append(dwdZjhm);
        sb.append(", dwdLoadtime=").append(dwdLoadtime);
        sb.append(", dwdUpdatetime=").append(dwdUpdatetime);
        sb.append(", depCode=").append(depCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}