package com.dao.entity.zjsouredata;

import java.io.Serializable;
import java.util.Date;

public class LdDwdGjXjTlspXxDs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ph
     *
     * @mbg.generated
     */
    private String ph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.xm
     *
     * @mbg.generated
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.xib
     *
     * @mbg.generated
     */
    private String xib;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.mz
     *
     * @mbg.generated
     */
    private String mz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq
     *
     * @mbg.generated
     */
    private String csrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq_dt
     *
     * @mbg.generated
     */
    private Date csrqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq_int
     *
     * @mbg.generated
     */
    private Integer csrqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.zjlx
     *
     * @mbg.generated
     */
    private String zjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.zjhm
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ry_xxdz
     *
     * @mbg.generated
     */
    private String ryXxdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.fcz
     *
     * @mbg.generated
     */
    private String fcz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ddz
     *
     * @mbg.generated
     */
    private String ddz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.cc
     *
     * @mbg.generated
     */
    private String cc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.cxh
     *
     * @mbg.generated
     */
    private String cxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.xwh
     *
     * @mbg.generated
     */
    private String xwh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.zxb
     *
     * @mbg.generated
     */
    private String zxb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.gxdbm
     *
     * @mbg.generated
     */
    private String gxdbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.gxdmc
     *
     * @mbg.generated
     */
    private String gxdmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.spch
     *
     * @mbg.generated
     */
    private String spch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.czyh
     *
     * @mbg.generated
     */
    private String czyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ckh
     *
     * @mbg.generated
     */
    private String ckh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj
     *
     * @mbg.generated
     */
    private String spsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj_dt
     *
     * @mbg.generated
     */
    private Date spsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj_int
     *
     * @mbg.generated
     */
    private Integer spsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.jlrksj
     *
     * @mbg.generated
     */
    private String jlrksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.rkwj
     *
     * @mbg.generated
     */
    private String rkwj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_xlbh
     *
     * @mbg.generated
     */
    private String tbXlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_rksj
     *
     * @mbg.generated
     */
    private String tbRksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_bjzd
     *
     * @mbg.generated
     */
    private String tbBjzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj
     *
     * @mbg.generated
     */
    private String fcsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj_dt
     *
     * @mbg.generated
     */
    private Date fcsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj_int
     *
     * @mbg.generated
     */
    private Integer fcsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj
     *
     * @mbg.generated
     */
    private String ddsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj_dt
     *
     * @mbg.generated
     */
    private Date ddsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj_int
     *
     * @mbg.generated
     */
    private Integer ddsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.jg2
     *
     * @mbg.generated
     */
    private String jg2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.jg4
     *
     * @mbg.generated
     */
    private String jg4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.jg6
     *
     * @mbg.generated
     */
    private String jg6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.gjlx
     *
     * @mbg.generated
     */
    private String gjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.kssjyyyy
     *
     * @mbg.generated
     */
    private String kssjyyyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.op_type
     *
     * @mbg.generated
     */
    private String opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.time_stamp
     *
     * @mbg.generated
     */
    private String timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.gmsfhm
     *
     * @mbg.generated
     */
    private String gmsfhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_zjhm
     *
     * @mbg.generated
     */
    private String dwdZjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_loadtime
     *
     * @mbg.generated
     */
    private String dwdLoadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_updatetime
     *
     * @mbg.generated
     */
    private String dwdUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_yxbz
     *
     * @mbg.generated
     */
    private String dwdYxbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.fq_week
     *
     * @mbg.generated
     */
    private String fqWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_gj_xj_tlsp_xx_ds.dep_code
     *
     * @mbg.generated
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.id
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.id
     *
     * @param id the value for ld_dwd_gj_xj_tlsp_xx_ds.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ph
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ph
     *
     * @mbg.generated
     */
    public String getPh() {
        return ph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ph
     *
     * @param ph the value for ld_dwd_gj_xj_tlsp_xx_ds.ph
     *
     * @mbg.generated
     */
    public void setPh(String ph) {
        this.ph = ph == null ? null : ph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.xm
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.xm
     *
     * @mbg.generated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.xm
     *
     * @param xm the value for ld_dwd_gj_xj_tlsp_xx_ds.xm
     *
     * @mbg.generated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.xib
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.xib
     *
     * @mbg.generated
     */
    public String getXib() {
        return xib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.xib
     *
     * @param xib the value for ld_dwd_gj_xj_tlsp_xx_ds.xib
     *
     * @mbg.generated
     */
    public void setXib(String xib) {
        this.xib = xib == null ? null : xib.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.mz
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.mz
     *
     * @mbg.generated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.mz
     *
     * @param mz the value for ld_dwd_gj_xj_tlsp_xx_ds.mz
     *
     * @mbg.generated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.csrq
     *
     * @mbg.generated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq
     *
     * @param csrq the value for ld_dwd_gj_xj_tlsp_xx_ds.csrq
     *
     * @mbg.generated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq_dt
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.csrq_dt
     *
     * @mbg.generated
     */
    public Date getCsrqDt() {
        return csrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq_dt
     *
     * @param csrqDt the value for ld_dwd_gj_xj_tlsp_xx_ds.csrq_dt
     *
     * @mbg.generated
     */
    public void setCsrqDt(Date csrqDt) {
        this.csrqDt = csrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq_int
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.csrq_int
     *
     * @mbg.generated
     */
    public Integer getCsrqInt() {
        return csrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.csrq_int
     *
     * @param csrqInt the value for ld_dwd_gj_xj_tlsp_xx_ds.csrq_int
     *
     * @mbg.generated
     */
    public void setCsrqInt(Integer csrqInt) {
        this.csrqInt = csrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.zjlx
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.zjlx
     *
     * @mbg.generated
     */
    public String getZjlx() {
        return zjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.zjlx
     *
     * @param zjlx the value for ld_dwd_gj_xj_tlsp_xx_ds.zjlx
     *
     * @mbg.generated
     */
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx == null ? null : zjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.zjhm
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.zjhm
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.zjhm
     *
     * @param zjhm the value for ld_dwd_gj_xj_tlsp_xx_ds.zjhm
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ry_xxdz
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ry_xxdz
     *
     * @mbg.generated
     */
    public String getRyXxdz() {
        return ryXxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ry_xxdz
     *
     * @param ryXxdz the value for ld_dwd_gj_xj_tlsp_xx_ds.ry_xxdz
     *
     * @mbg.generated
     */
    public void setRyXxdz(String ryXxdz) {
        this.ryXxdz = ryXxdz == null ? null : ryXxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcz
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.fcz
     *
     * @mbg.generated
     */
    public String getFcz() {
        return fcz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcz
     *
     * @param fcz the value for ld_dwd_gj_xj_tlsp_xx_ds.fcz
     *
     * @mbg.generated
     */
    public void setFcz(String fcz) {
        this.fcz = fcz == null ? null : fcz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddz
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ddz
     *
     * @mbg.generated
     */
    public String getDdz() {
        return ddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddz
     *
     * @param ddz the value for ld_dwd_gj_xj_tlsp_xx_ds.ddz
     *
     * @mbg.generated
     */
    public void setDdz(String ddz) {
        this.ddz = ddz == null ? null : ddz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.cc
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.cc
     *
     * @mbg.generated
     */
    public String getCc() {
        return cc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.cc
     *
     * @param cc the value for ld_dwd_gj_xj_tlsp_xx_ds.cc
     *
     * @mbg.generated
     */
    public void setCc(String cc) {
        this.cc = cc == null ? null : cc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.cxh
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.cxh
     *
     * @mbg.generated
     */
    public String getCxh() {
        return cxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.cxh
     *
     * @param cxh the value for ld_dwd_gj_xj_tlsp_xx_ds.cxh
     *
     * @mbg.generated
     */
    public void setCxh(String cxh) {
        this.cxh = cxh == null ? null : cxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.xwh
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.xwh
     *
     * @mbg.generated
     */
    public String getXwh() {
        return xwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.xwh
     *
     * @param xwh the value for ld_dwd_gj_xj_tlsp_xx_ds.xwh
     *
     * @mbg.generated
     */
    public void setXwh(String xwh) {
        this.xwh = xwh == null ? null : xwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.zxb
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.zxb
     *
     * @mbg.generated
     */
    public String getZxb() {
        return zxb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.zxb
     *
     * @param zxb the value for ld_dwd_gj_xj_tlsp_xx_ds.zxb
     *
     * @mbg.generated
     */
    public void setZxb(String zxb) {
        this.zxb = zxb == null ? null : zxb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gxdbm
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.gxdbm
     *
     * @mbg.generated
     */
    public String getGxdbm() {
        return gxdbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gxdbm
     *
     * @param gxdbm the value for ld_dwd_gj_xj_tlsp_xx_ds.gxdbm
     *
     * @mbg.generated
     */
    public void setGxdbm(String gxdbm) {
        this.gxdbm = gxdbm == null ? null : gxdbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gxdmc
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.gxdmc
     *
     * @mbg.generated
     */
    public String getGxdmc() {
        return gxdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gxdmc
     *
     * @param gxdmc the value for ld_dwd_gj_xj_tlsp_xx_ds.gxdmc
     *
     * @mbg.generated
     */
    public void setGxdmc(String gxdmc) {
        this.gxdmc = gxdmc == null ? null : gxdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spch
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.spch
     *
     * @mbg.generated
     */
    public String getSpch() {
        return spch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spch
     *
     * @param spch the value for ld_dwd_gj_xj_tlsp_xx_ds.spch
     *
     * @mbg.generated
     */
    public void setSpch(String spch) {
        this.spch = spch == null ? null : spch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.czyh
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.czyh
     *
     * @mbg.generated
     */
    public String getCzyh() {
        return czyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.czyh
     *
     * @param czyh the value for ld_dwd_gj_xj_tlsp_xx_ds.czyh
     *
     * @mbg.generated
     */
    public void setCzyh(String czyh) {
        this.czyh = czyh == null ? null : czyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ckh
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ckh
     *
     * @mbg.generated
     */
    public String getCkh() {
        return ckh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ckh
     *
     * @param ckh the value for ld_dwd_gj_xj_tlsp_xx_ds.ckh
     *
     * @mbg.generated
     */
    public void setCkh(String ckh) {
        this.ckh = ckh == null ? null : ckh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.spsj
     *
     * @mbg.generated
     */
    public String getSpsj() {
        return spsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj
     *
     * @param spsj the value for ld_dwd_gj_xj_tlsp_xx_ds.spsj
     *
     * @mbg.generated
     */
    public void setSpsj(String spsj) {
        this.spsj = spsj == null ? null : spsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj_dt
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.spsj_dt
     *
     * @mbg.generated
     */
    public Date getSpsjDt() {
        return spsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj_dt
     *
     * @param spsjDt the value for ld_dwd_gj_xj_tlsp_xx_ds.spsj_dt
     *
     * @mbg.generated
     */
    public void setSpsjDt(Date spsjDt) {
        this.spsjDt = spsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj_int
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.spsj_int
     *
     * @mbg.generated
     */
    public Integer getSpsjInt() {
        return spsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.spsj_int
     *
     * @param spsjInt the value for ld_dwd_gj_xj_tlsp_xx_ds.spsj_int
     *
     * @mbg.generated
     */
    public void setSpsjInt(Integer spsjInt) {
        this.spsjInt = spsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jlrksj
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.jlrksj
     *
     * @mbg.generated
     */
    public String getJlrksj() {
        return jlrksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jlrksj
     *
     * @param jlrksj the value for ld_dwd_gj_xj_tlsp_xx_ds.jlrksj
     *
     * @mbg.generated
     */
    public void setJlrksj(String jlrksj) {
        this.jlrksj = jlrksj == null ? null : jlrksj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.rkwj
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.rkwj
     *
     * @mbg.generated
     */
    public String getRkwj() {
        return rkwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.rkwj
     *
     * @param rkwj the value for ld_dwd_gj_xj_tlsp_xx_ds.rkwj
     *
     * @mbg.generated
     */
    public void setRkwj(String rkwj) {
        this.rkwj = rkwj == null ? null : rkwj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_xlbh
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.tb_xlbh
     *
     * @mbg.generated
     */
    public String getTbXlbh() {
        return tbXlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_xlbh
     *
     * @param tbXlbh the value for ld_dwd_gj_xj_tlsp_xx_ds.tb_xlbh
     *
     * @mbg.generated
     */
    public void setTbXlbh(String tbXlbh) {
        this.tbXlbh = tbXlbh == null ? null : tbXlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_rksj
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.tb_rksj
     *
     * @mbg.generated
     */
    public String getTbRksj() {
        return tbRksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_rksj
     *
     * @param tbRksj the value for ld_dwd_gj_xj_tlsp_xx_ds.tb_rksj
     *
     * @mbg.generated
     */
    public void setTbRksj(String tbRksj) {
        this.tbRksj = tbRksj == null ? null : tbRksj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_bjzd
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.tb_bjzd
     *
     * @mbg.generated
     */
    public String getTbBjzd() {
        return tbBjzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.tb_bjzd
     *
     * @param tbBjzd the value for ld_dwd_gj_xj_tlsp_xx_ds.tb_bjzd
     *
     * @mbg.generated
     */
    public void setTbBjzd(String tbBjzd) {
        this.tbBjzd = tbBjzd == null ? null : tbBjzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.fcsj
     *
     * @mbg.generated
     */
    public String getFcsj() {
        return fcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj
     *
     * @param fcsj the value for ld_dwd_gj_xj_tlsp_xx_ds.fcsj
     *
     * @mbg.generated
     */
    public void setFcsj(String fcsj) {
        this.fcsj = fcsj == null ? null : fcsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj_dt
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.fcsj_dt
     *
     * @mbg.generated
     */
    public Date getFcsjDt() {
        return fcsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj_dt
     *
     * @param fcsjDt the value for ld_dwd_gj_xj_tlsp_xx_ds.fcsj_dt
     *
     * @mbg.generated
     */
    public void setFcsjDt(Date fcsjDt) {
        this.fcsjDt = fcsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj_int
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.fcsj_int
     *
     * @mbg.generated
     */
    public Integer getFcsjInt() {
        return fcsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fcsj_int
     *
     * @param fcsjInt the value for ld_dwd_gj_xj_tlsp_xx_ds.fcsj_int
     *
     * @mbg.generated
     */
    public void setFcsjInt(Integer fcsjInt) {
        this.fcsjInt = fcsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ddsj
     *
     * @mbg.generated
     */
    public String getDdsj() {
        return ddsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj
     *
     * @param ddsj the value for ld_dwd_gj_xj_tlsp_xx_ds.ddsj
     *
     * @mbg.generated
     */
    public void setDdsj(String ddsj) {
        this.ddsj = ddsj == null ? null : ddsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj_dt
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ddsj_dt
     *
     * @mbg.generated
     */
    public Date getDdsjDt() {
        return ddsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj_dt
     *
     * @param ddsjDt the value for ld_dwd_gj_xj_tlsp_xx_ds.ddsj_dt
     *
     * @mbg.generated
     */
    public void setDdsjDt(Date ddsjDt) {
        this.ddsjDt = ddsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj_int
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.ddsj_int
     *
     * @mbg.generated
     */
    public Integer getDdsjInt() {
        return ddsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.ddsj_int
     *
     * @param ddsjInt the value for ld_dwd_gj_xj_tlsp_xx_ds.ddsj_int
     *
     * @mbg.generated
     */
    public void setDdsjInt(Integer ddsjInt) {
        this.ddsjInt = ddsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jg2
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.jg2
     *
     * @mbg.generated
     */
    public String getJg2() {
        return jg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jg2
     *
     * @param jg2 the value for ld_dwd_gj_xj_tlsp_xx_ds.jg2
     *
     * @mbg.generated
     */
    public void setJg2(String jg2) {
        this.jg2 = jg2 == null ? null : jg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jg4
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.jg4
     *
     * @mbg.generated
     */
    public String getJg4() {
        return jg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jg4
     *
     * @param jg4 the value for ld_dwd_gj_xj_tlsp_xx_ds.jg4
     *
     * @mbg.generated
     */
    public void setJg4(String jg4) {
        this.jg4 = jg4 == null ? null : jg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jg6
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.jg6
     *
     * @mbg.generated
     */
    public String getJg6() {
        return jg6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.jg6
     *
     * @param jg6 the value for ld_dwd_gj_xj_tlsp_xx_ds.jg6
     *
     * @mbg.generated
     */
    public void setJg6(String jg6) {
        this.jg6 = jg6 == null ? null : jg6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gjlx
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.gjlx
     *
     * @mbg.generated
     */
    public String getGjlx() {
        return gjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gjlx
     *
     * @param gjlx the value for ld_dwd_gj_xj_tlsp_xx_ds.gjlx
     *
     * @mbg.generated
     */
    public void setGjlx(String gjlx) {
        this.gjlx = gjlx == null ? null : gjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.kssjyyyy
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.kssjyyyy
     *
     * @mbg.generated
     */
    public String getKssjyyyy() {
        return kssjyyyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.kssjyyyy
     *
     * @param kssjyyyy the value for ld_dwd_gj_xj_tlsp_xx_ds.kssjyyyy
     *
     * @mbg.generated
     */
    public void setKssjyyyy(String kssjyyyy) {
        this.kssjyyyy = kssjyyyy == null ? null : kssjyyyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.op_type
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.op_type
     *
     * @mbg.generated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.op_type
     *
     * @param opType the value for ld_dwd_gj_xj_tlsp_xx_ds.op_type
     *
     * @mbg.generated
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.time_stamp
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.time_stamp
     *
     * @mbg.generated
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.time_stamp
     *
     * @param timeStamp the value for ld_dwd_gj_xj_tlsp_xx_ds.time_stamp
     *
     * @mbg.generated
     */
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp == null ? null : timeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gmsfhm
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.gmsfhm
     *
     * @mbg.generated
     */
    public String getGmsfhm() {
        return gmsfhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.gmsfhm
     *
     * @param gmsfhm the value for ld_dwd_gj_xj_tlsp_xx_ds.gmsfhm
     *
     * @mbg.generated
     */
    public void setGmsfhm(String gmsfhm) {
        this.gmsfhm = gmsfhm == null ? null : gmsfhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_zjhm
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.dwd_zjhm
     *
     * @mbg.generated
     */
    public String getDwdZjhm() {
        return dwdZjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_zjhm
     *
     * @param dwdZjhm the value for ld_dwd_gj_xj_tlsp_xx_ds.dwd_zjhm
     *
     * @mbg.generated
     */
    public void setDwdZjhm(String dwdZjhm) {
        this.dwdZjhm = dwdZjhm == null ? null : dwdZjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_loadtime
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.dwd_loadtime
     *
     * @mbg.generated
     */
    public String getDwdLoadtime() {
        return dwdLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_loadtime
     *
     * @param dwdLoadtime the value for ld_dwd_gj_xj_tlsp_xx_ds.dwd_loadtime
     *
     * @mbg.generated
     */
    public void setDwdLoadtime(String dwdLoadtime) {
        this.dwdLoadtime = dwdLoadtime == null ? null : dwdLoadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_updatetime
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.dwd_updatetime
     *
     * @mbg.generated
     */
    public String getDwdUpdatetime() {
        return dwdUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_updatetime
     *
     * @param dwdUpdatetime the value for ld_dwd_gj_xj_tlsp_xx_ds.dwd_updatetime
     *
     * @mbg.generated
     */
    public void setDwdUpdatetime(String dwdUpdatetime) {
        this.dwdUpdatetime = dwdUpdatetime == null ? null : dwdUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_yxbz
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.dwd_yxbz
     *
     * @mbg.generated
     */
    public String getDwdYxbz() {
        return dwdYxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dwd_yxbz
     *
     * @param dwdYxbz the value for ld_dwd_gj_xj_tlsp_xx_ds.dwd_yxbz
     *
     * @mbg.generated
     */
    public void setDwdYxbz(String dwdYxbz) {
        this.dwdYxbz = dwdYxbz == null ? null : dwdYxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fq_week
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.fq_week
     *
     * @mbg.generated
     */
    public String getFqWeek() {
        return fqWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.fq_week
     *
     * @param fqWeek the value for ld_dwd_gj_xj_tlsp_xx_ds.fq_week
     *
     * @mbg.generated
     */
    public void setFqWeek(String fqWeek) {
        this.fqWeek = fqWeek == null ? null : fqWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dep_code
     *
     * @return the value of ld_dwd_gj_xj_tlsp_xx_ds.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_gj_xj_tlsp_xx_ds.dep_code
     *
     * @param depCode the value for ld_dwd_gj_xj_tlsp_xx_ds.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_gj_xj_tlsp_xx_ds
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ph=").append(ph);
        sb.append(", xm=").append(xm);
        sb.append(", xib=").append(xib);
        sb.append(", mz=").append(mz);
        sb.append(", csrq=").append(csrq);
        sb.append(", csrqDt=").append(csrqDt);
        sb.append(", csrqInt=").append(csrqInt);
        sb.append(", zjlx=").append(zjlx);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", ryXxdz=").append(ryXxdz);
        sb.append(", fcz=").append(fcz);
        sb.append(", ddz=").append(ddz);
        sb.append(", cc=").append(cc);
        sb.append(", cxh=").append(cxh);
        sb.append(", xwh=").append(xwh);
        sb.append(", zxb=").append(zxb);
        sb.append(", gxdbm=").append(gxdbm);
        sb.append(", gxdmc=").append(gxdmc);
        sb.append(", spch=").append(spch);
        sb.append(", czyh=").append(czyh);
        sb.append(", ckh=").append(ckh);
        sb.append(", spsj=").append(spsj);
        sb.append(", spsjDt=").append(spsjDt);
        sb.append(", spsjInt=").append(spsjInt);
        sb.append(", jlrksj=").append(jlrksj);
        sb.append(", rkwj=").append(rkwj);
        sb.append(", tbXlbh=").append(tbXlbh);
        sb.append(", tbRksj=").append(tbRksj);
        sb.append(", tbBjzd=").append(tbBjzd);
        sb.append(", fcsj=").append(fcsj);
        sb.append(", fcsjDt=").append(fcsjDt);
        sb.append(", fcsjInt=").append(fcsjInt);
        sb.append(", ddsj=").append(ddsj);
        sb.append(", ddsjDt=").append(ddsjDt);
        sb.append(", ddsjInt=").append(ddsjInt);
        sb.append(", jg2=").append(jg2);
        sb.append(", jg4=").append(jg4);
        sb.append(", jg6=").append(jg6);
        sb.append(", gjlx=").append(gjlx);
        sb.append(", kssjyyyy=").append(kssjyyyy);
        sb.append(", opType=").append(opType);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", gmsfhm=").append(gmsfhm);
        sb.append(", dwdZjhm=").append(dwdZjhm);
        sb.append(", dwdLoadtime=").append(dwdLoadtime);
        sb.append(", dwdUpdatetime=").append(dwdUpdatetime);
        sb.append(", dwdYxbz=").append(dwdYxbz);
        sb.append(", fqWeek=").append(fqWeek);
        sb.append(", depCode=").append(depCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}