package com.dao.entity.zjsouredata;

import java.io.Serializable;
import java.util.Date;

public class LdDwdRkBfCrjryjlDd implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crjrylbdm
     *
     * @mbg.generated
     */
    private String crjrylbdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crjrylb
     *
     * @mbg.generated
     */
    private String crjrylb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.xm
     *
     * @mbg.generated
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.gjhdqdm
     *
     * @mbg.generated
     */
    private String gjhdqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.gjhdq
     *
     * @mbg.generated
     */
    private String gjhdq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.xbdm
     *
     * @mbg.generated
     */
    private String xbdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.xb
     *
     * @mbg.generated
     */
    private String xb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.csrq
     *
     * @mbg.generated
     */
    private String csrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.csrq_dt
     *
     * @mbg.generated
     */
    private Date csrqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.csrq_int
     *
     * @mbg.generated
     */
    private Integer csrqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.cyzjlbdm
     *
     * @mbg.generated
     */
    private String cyzjlbdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.cyzjlb
     *
     * @mbg.generated
     */
    private String cyzjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.zjhm
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.zgqzzldm
     *
     * @mbg.generated
     */
    private String zgqzzldm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.zgqzzl
     *
     * @mbg.generated
     */
    private String zgqzzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crrq
     *
     * @mbg.generated
     */
    private String crrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crrq_dt
     *
     * @mbg.generated
     */
    private Date crrqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crrq_int
     *
     * @mbg.generated
     */
    private Integer crrqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crsj
     *
     * @mbg.generated
     */
    private String crsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj
     *
     * @mbg.generated
     */
    private String crrqsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj_dt
     *
     * @mbg.generated
     */
    private Date crrqsjDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj_int
     *
     * @mbg.generated
     */
    private Integer crrqsjInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crkadm
     *
     * @mbg.generated
     */
    private String crkadm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crka
     *
     * @mbg.generated
     */
    private String crka;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.jtfsdm
     *
     * @mbg.generated
     */
    private String jtfsdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.jtfs
     *
     * @mbg.generated
     */
    private String jtfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.jtgjlb
     *
     * @mbg.generated
     */
    private String jtgjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.qw_gjhdqdm
     *
     * @mbg.generated
     */
    private String qwGjhdqdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.qw_gjhdq
     *
     * @mbg.generated
     */
    private String qwGjhdq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.fzddm
     *
     * @mbg.generated
     */
    private String fzddm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.fzd
     *
     * @mbg.generated
     */
    private String fzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crjsy
     *
     * @mbg.generated
     */
    private String crjsy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.jcyh
     *
     * @mbg.generated
     */
    private String jcyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.tdh
     *
     * @mbg.generated
     */
    private String tdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.nbth
     *
     * @mbg.generated
     */
    private String nbth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.lxth
     *
     * @mbg.generated
     */
    private String lxth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.ccxm_bz
     *
     * @mbg.generated
     */
    private String ccxmBz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.ynzsm
     *
     * @mbg.generated
     */
    private String ynzsm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dezh
     *
     * @mbg.generated
     */
    private String dezh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dezldm
     *
     * @mbg.generated
     */
    private String dezldm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dezl
     *
     * @mbg.generated
     */
    private String dezl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.decsrq
     *
     * @mbg.generated
     */
    private String decsrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.decsrq_dt
     *
     * @mbg.generated
     */
    private Date decsrqDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.decsrq_int
     *
     * @mbg.generated
     */
    private Integer decsrqInt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dexm
     *
     * @mbg.generated
     */
    private String dexm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.ri
     *
     * @mbg.generated
     */
    private String ri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.xmhypy
     *
     * @mbg.generated
     */
    private String xmhypy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.jtxm
     *
     * @mbg.generated
     */
    private String jtxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.bmdm
     *
     * @mbg.generated
     */
    private String bmdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.bm
     *
     * @mbg.generated
     */
    private String bm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.wybs
     *
     * @mbg.generated
     */
    private String wybs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.mzdm
     *
     * @mbg.generated
     */
    private String mzdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.mz
     *
     * @mbg.generated
     */
    private String mz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.zdydm
     *
     * @mbg.generated
     */
    private String zdydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.zztdbj
     *
     * @mbg.generated
     */
    private String zztdbj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.htblbj
     *
     * @mbg.generated
     */
    private String htblbj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.crbz
     *
     * @mbg.generated
     */
    private String crbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.bgczy
     *
     * @mbg.generated
     */
    private String bgczy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.bgczsj
     *
     * @mbg.generated
     */
    private String bgczsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.qzh
     *
     * @mbg.generated
     */
    private String qzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.tlq
     *
     * @mbg.generated
     */
    private String tlq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.czmc
     *
     * @mbg.generated
     */
    private String czmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.bf_rksj
     *
     * @mbg.generated
     */
    private String bfRksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.tb_bjzd
     *
     * @mbg.generated
     */
    private String tbBjzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.tb_xlbh
     *
     * @mbg.generated
     */
    private String tbXlbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.tb_rksj
     *
     * @mbg.generated
     */
    private String tbRksj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.op_type
     *
     * @mbg.generated
     */
    private String opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.time_stamp
     *
     * @mbg.generated
     */
    private String timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.gmsfhm
     *
     * @mbg.generated
     */
    private String gmsfhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dwd_zjhm
     *
     * @mbg.generated
     */
    private String dwdZjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dwd_loadtime
     *
     * @mbg.generated
     */
    private String dwdLoadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dwd_updatetime
     *
     * @mbg.generated
     */
    private String dwdUpdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dwd_yxbz
     *
     * @mbg.generated
     */
    private String dwdYxbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_dwd_rk_bf_crjryjl_dd.dep_code
     *
     * @mbg.generated
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ld_dwd_rk_bf_crjryjl_dd
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.id
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.id
     *
     * @param id the value for ld_dwd_rk_bf_crjryjl_dd.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crjrylbdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crjrylbdm
     *
     * @mbg.generated
     */
    public String getCrjrylbdm() {
        return crjrylbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crjrylbdm
     *
     * @param crjrylbdm the value for ld_dwd_rk_bf_crjryjl_dd.crjrylbdm
     *
     * @mbg.generated
     */
    public void setCrjrylbdm(String crjrylbdm) {
        this.crjrylbdm = crjrylbdm == null ? null : crjrylbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crjrylb
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crjrylb
     *
     * @mbg.generated
     */
    public String getCrjrylb() {
        return crjrylb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crjrylb
     *
     * @param crjrylb the value for ld_dwd_rk_bf_crjryjl_dd.crjrylb
     *
     * @mbg.generated
     */
    public void setCrjrylb(String crjrylb) {
        this.crjrylb = crjrylb == null ? null : crjrylb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.xm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.xm
     *
     * @mbg.generated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.xm
     *
     * @param xm the value for ld_dwd_rk_bf_crjryjl_dd.xm
     *
     * @mbg.generated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.gjhdqdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.gjhdqdm
     *
     * @mbg.generated
     */
    public String getGjhdqdm() {
        return gjhdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.gjhdqdm
     *
     * @param gjhdqdm the value for ld_dwd_rk_bf_crjryjl_dd.gjhdqdm
     *
     * @mbg.generated
     */
    public void setGjhdqdm(String gjhdqdm) {
        this.gjhdqdm = gjhdqdm == null ? null : gjhdqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.gjhdq
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.gjhdq
     *
     * @mbg.generated
     */
    public String getGjhdq() {
        return gjhdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.gjhdq
     *
     * @param gjhdq the value for ld_dwd_rk_bf_crjryjl_dd.gjhdq
     *
     * @mbg.generated
     */
    public void setGjhdq(String gjhdq) {
        this.gjhdq = gjhdq == null ? null : gjhdq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.xbdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.xbdm
     *
     * @mbg.generated
     */
    public String getXbdm() {
        return xbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.xbdm
     *
     * @param xbdm the value for ld_dwd_rk_bf_crjryjl_dd.xbdm
     *
     * @mbg.generated
     */
    public void setXbdm(String xbdm) {
        this.xbdm = xbdm == null ? null : xbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.xb
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.xb
     *
     * @mbg.generated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.xb
     *
     * @param xb the value for ld_dwd_rk_bf_crjryjl_dd.xb
     *
     * @mbg.generated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.csrq
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.csrq
     *
     * @mbg.generated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.csrq
     *
     * @param csrq the value for ld_dwd_rk_bf_crjryjl_dd.csrq
     *
     * @mbg.generated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.csrq_dt
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.csrq_dt
     *
     * @mbg.generated
     */
    public Date getCsrqDt() {
        return csrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.csrq_dt
     *
     * @param csrqDt the value for ld_dwd_rk_bf_crjryjl_dd.csrq_dt
     *
     * @mbg.generated
     */
    public void setCsrqDt(Date csrqDt) {
        this.csrqDt = csrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.csrq_int
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.csrq_int
     *
     * @mbg.generated
     */
    public Integer getCsrqInt() {
        return csrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.csrq_int
     *
     * @param csrqInt the value for ld_dwd_rk_bf_crjryjl_dd.csrq_int
     *
     * @mbg.generated
     */
    public void setCsrqInt(Integer csrqInt) {
        this.csrqInt = csrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.cyzjlbdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.cyzjlbdm
     *
     * @mbg.generated
     */
    public String getCyzjlbdm() {
        return cyzjlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.cyzjlbdm
     *
     * @param cyzjlbdm the value for ld_dwd_rk_bf_crjryjl_dd.cyzjlbdm
     *
     * @mbg.generated
     */
    public void setCyzjlbdm(String cyzjlbdm) {
        this.cyzjlbdm = cyzjlbdm == null ? null : cyzjlbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.cyzjlb
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.cyzjlb
     *
     * @mbg.generated
     */
    public String getCyzjlb() {
        return cyzjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.cyzjlb
     *
     * @param cyzjlb the value for ld_dwd_rk_bf_crjryjl_dd.cyzjlb
     *
     * @mbg.generated
     */
    public void setCyzjlb(String cyzjlb) {
        this.cyzjlb = cyzjlb == null ? null : cyzjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.zjhm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.zjhm
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.zjhm
     *
     * @param zjhm the value for ld_dwd_rk_bf_crjryjl_dd.zjhm
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.zgqzzldm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.zgqzzldm
     *
     * @mbg.generated
     */
    public String getZgqzzldm() {
        return zgqzzldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.zgqzzldm
     *
     * @param zgqzzldm the value for ld_dwd_rk_bf_crjryjl_dd.zgqzzldm
     *
     * @mbg.generated
     */
    public void setZgqzzldm(String zgqzzldm) {
        this.zgqzzldm = zgqzzldm == null ? null : zgqzzldm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.zgqzzl
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.zgqzzl
     *
     * @mbg.generated
     */
    public String getZgqzzl() {
        return zgqzzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.zgqzzl
     *
     * @param zgqzzl the value for ld_dwd_rk_bf_crjryjl_dd.zgqzzl
     *
     * @mbg.generated
     */
    public void setZgqzzl(String zgqzzl) {
        this.zgqzzl = zgqzzl == null ? null : zgqzzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrq
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crrq
     *
     * @mbg.generated
     */
    public String getCrrq() {
        return crrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrq
     *
     * @param crrq the value for ld_dwd_rk_bf_crjryjl_dd.crrq
     *
     * @mbg.generated
     */
    public void setCrrq(String crrq) {
        this.crrq = crrq == null ? null : crrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrq_dt
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crrq_dt
     *
     * @mbg.generated
     */
    public Date getCrrqDt() {
        return crrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrq_dt
     *
     * @param crrqDt the value for ld_dwd_rk_bf_crjryjl_dd.crrq_dt
     *
     * @mbg.generated
     */
    public void setCrrqDt(Date crrqDt) {
        this.crrqDt = crrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrq_int
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crrq_int
     *
     * @mbg.generated
     */
    public Integer getCrrqInt() {
        return crrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrq_int
     *
     * @param crrqInt the value for ld_dwd_rk_bf_crjryjl_dd.crrq_int
     *
     * @mbg.generated
     */
    public void setCrrqInt(Integer crrqInt) {
        this.crrqInt = crrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crsj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crsj
     *
     * @mbg.generated
     */
    public String getCrsj() {
        return crsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crsj
     *
     * @param crsj the value for ld_dwd_rk_bf_crjryjl_dd.crsj
     *
     * @mbg.generated
     */
    public void setCrsj(String crsj) {
        this.crsj = crsj == null ? null : crsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crrqsj
     *
     * @mbg.generated
     */
    public String getCrrqsj() {
        return crrqsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj
     *
     * @param crrqsj the value for ld_dwd_rk_bf_crjryjl_dd.crrqsj
     *
     * @mbg.generated
     */
    public void setCrrqsj(String crrqsj) {
        this.crrqsj = crrqsj == null ? null : crrqsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj_dt
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crrqsj_dt
     *
     * @mbg.generated
     */
    public Date getCrrqsjDt() {
        return crrqsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj_dt
     *
     * @param crrqsjDt the value for ld_dwd_rk_bf_crjryjl_dd.crrqsj_dt
     *
     * @mbg.generated
     */
    public void setCrrqsjDt(Date crrqsjDt) {
        this.crrqsjDt = crrqsjDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj_int
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crrqsj_int
     *
     * @mbg.generated
     */
    public Integer getCrrqsjInt() {
        return crrqsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crrqsj_int
     *
     * @param crrqsjInt the value for ld_dwd_rk_bf_crjryjl_dd.crrqsj_int
     *
     * @mbg.generated
     */
    public void setCrrqsjInt(Integer crrqsjInt) {
        this.crrqsjInt = crrqsjInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crkadm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crkadm
     *
     * @mbg.generated
     */
    public String getCrkadm() {
        return crkadm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crkadm
     *
     * @param crkadm the value for ld_dwd_rk_bf_crjryjl_dd.crkadm
     *
     * @mbg.generated
     */
    public void setCrkadm(String crkadm) {
        this.crkadm = crkadm == null ? null : crkadm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crka
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crka
     *
     * @mbg.generated
     */
    public String getCrka() {
        return crka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crka
     *
     * @param crka the value for ld_dwd_rk_bf_crjryjl_dd.crka
     *
     * @mbg.generated
     */
    public void setCrka(String crka) {
        this.crka = crka == null ? null : crka.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtfsdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.jtfsdm
     *
     * @mbg.generated
     */
    public String getJtfsdm() {
        return jtfsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtfsdm
     *
     * @param jtfsdm the value for ld_dwd_rk_bf_crjryjl_dd.jtfsdm
     *
     * @mbg.generated
     */
    public void setJtfsdm(String jtfsdm) {
        this.jtfsdm = jtfsdm == null ? null : jtfsdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtfs
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.jtfs
     *
     * @mbg.generated
     */
    public String getJtfs() {
        return jtfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtfs
     *
     * @param jtfs the value for ld_dwd_rk_bf_crjryjl_dd.jtfs
     *
     * @mbg.generated
     */
    public void setJtfs(String jtfs) {
        this.jtfs = jtfs == null ? null : jtfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtgjlb
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.jtgjlb
     *
     * @mbg.generated
     */
    public String getJtgjlb() {
        return jtgjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtgjlb
     *
     * @param jtgjlb the value for ld_dwd_rk_bf_crjryjl_dd.jtgjlb
     *
     * @mbg.generated
     */
    public void setJtgjlb(String jtgjlb) {
        this.jtgjlb = jtgjlb == null ? null : jtgjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.qw_gjhdqdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.qw_gjhdqdm
     *
     * @mbg.generated
     */
    public String getQwGjhdqdm() {
        return qwGjhdqdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.qw_gjhdqdm
     *
     * @param qwGjhdqdm the value for ld_dwd_rk_bf_crjryjl_dd.qw_gjhdqdm
     *
     * @mbg.generated
     */
    public void setQwGjhdqdm(String qwGjhdqdm) {
        this.qwGjhdqdm = qwGjhdqdm == null ? null : qwGjhdqdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.qw_gjhdq
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.qw_gjhdq
     *
     * @mbg.generated
     */
    public String getQwGjhdq() {
        return qwGjhdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.qw_gjhdq
     *
     * @param qwGjhdq the value for ld_dwd_rk_bf_crjryjl_dd.qw_gjhdq
     *
     * @mbg.generated
     */
    public void setQwGjhdq(String qwGjhdq) {
        this.qwGjhdq = qwGjhdq == null ? null : qwGjhdq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.fzddm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.fzddm
     *
     * @mbg.generated
     */
    public String getFzddm() {
        return fzddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.fzddm
     *
     * @param fzddm the value for ld_dwd_rk_bf_crjryjl_dd.fzddm
     *
     * @mbg.generated
     */
    public void setFzddm(String fzddm) {
        this.fzddm = fzddm == null ? null : fzddm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.fzd
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.fzd
     *
     * @mbg.generated
     */
    public String getFzd() {
        return fzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.fzd
     *
     * @param fzd the value for ld_dwd_rk_bf_crjryjl_dd.fzd
     *
     * @mbg.generated
     */
    public void setFzd(String fzd) {
        this.fzd = fzd == null ? null : fzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crjsy
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crjsy
     *
     * @mbg.generated
     */
    public String getCrjsy() {
        return crjsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crjsy
     *
     * @param crjsy the value for ld_dwd_rk_bf_crjryjl_dd.crjsy
     *
     * @mbg.generated
     */
    public void setCrjsy(String crjsy) {
        this.crjsy = crjsy == null ? null : crjsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.jcyh
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.jcyh
     *
     * @mbg.generated
     */
    public String getJcyh() {
        return jcyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.jcyh
     *
     * @param jcyh the value for ld_dwd_rk_bf_crjryjl_dd.jcyh
     *
     * @mbg.generated
     */
    public void setJcyh(String jcyh) {
        this.jcyh = jcyh == null ? null : jcyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.tdh
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.tdh
     *
     * @mbg.generated
     */
    public String getTdh() {
        return tdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.tdh
     *
     * @param tdh the value for ld_dwd_rk_bf_crjryjl_dd.tdh
     *
     * @mbg.generated
     */
    public void setTdh(String tdh) {
        this.tdh = tdh == null ? null : tdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.nbth
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.nbth
     *
     * @mbg.generated
     */
    public String getNbth() {
        return nbth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.nbth
     *
     * @param nbth the value for ld_dwd_rk_bf_crjryjl_dd.nbth
     *
     * @mbg.generated
     */
    public void setNbth(String nbth) {
        this.nbth = nbth == null ? null : nbth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.lxth
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.lxth
     *
     * @mbg.generated
     */
    public String getLxth() {
        return lxth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.lxth
     *
     * @param lxth the value for ld_dwd_rk_bf_crjryjl_dd.lxth
     *
     * @mbg.generated
     */
    public void setLxth(String lxth) {
        this.lxth = lxth == null ? null : lxth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.ccxm_bz
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.ccxm_bz
     *
     * @mbg.generated
     */
    public String getCcxmBz() {
        return ccxmBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.ccxm_bz
     *
     * @param ccxmBz the value for ld_dwd_rk_bf_crjryjl_dd.ccxm_bz
     *
     * @mbg.generated
     */
    public void setCcxmBz(String ccxmBz) {
        this.ccxmBz = ccxmBz == null ? null : ccxmBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.ynzsm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.ynzsm
     *
     * @mbg.generated
     */
    public String getYnzsm() {
        return ynzsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.ynzsm
     *
     * @param ynzsm the value for ld_dwd_rk_bf_crjryjl_dd.ynzsm
     *
     * @mbg.generated
     */
    public void setYnzsm(String ynzsm) {
        this.ynzsm = ynzsm == null ? null : ynzsm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dezh
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dezh
     *
     * @mbg.generated
     */
    public String getDezh() {
        return dezh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dezh
     *
     * @param dezh the value for ld_dwd_rk_bf_crjryjl_dd.dezh
     *
     * @mbg.generated
     */
    public void setDezh(String dezh) {
        this.dezh = dezh == null ? null : dezh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dezldm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dezldm
     *
     * @mbg.generated
     */
    public String getDezldm() {
        return dezldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dezldm
     *
     * @param dezldm the value for ld_dwd_rk_bf_crjryjl_dd.dezldm
     *
     * @mbg.generated
     */
    public void setDezldm(String dezldm) {
        this.dezldm = dezldm == null ? null : dezldm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dezl
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dezl
     *
     * @mbg.generated
     */
    public String getDezl() {
        return dezl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dezl
     *
     * @param dezl the value for ld_dwd_rk_bf_crjryjl_dd.dezl
     *
     * @mbg.generated
     */
    public void setDezl(String dezl) {
        this.dezl = dezl == null ? null : dezl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.decsrq
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.decsrq
     *
     * @mbg.generated
     */
    public String getDecsrq() {
        return decsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.decsrq
     *
     * @param decsrq the value for ld_dwd_rk_bf_crjryjl_dd.decsrq
     *
     * @mbg.generated
     */
    public void setDecsrq(String decsrq) {
        this.decsrq = decsrq == null ? null : decsrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.decsrq_dt
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.decsrq_dt
     *
     * @mbg.generated
     */
    public Date getDecsrqDt() {
        return decsrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.decsrq_dt
     *
     * @param decsrqDt the value for ld_dwd_rk_bf_crjryjl_dd.decsrq_dt
     *
     * @mbg.generated
     */
    public void setDecsrqDt(Date decsrqDt) {
        this.decsrqDt = decsrqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.decsrq_int
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.decsrq_int
     *
     * @mbg.generated
     */
    public Integer getDecsrqInt() {
        return decsrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.decsrq_int
     *
     * @param decsrqInt the value for ld_dwd_rk_bf_crjryjl_dd.decsrq_int
     *
     * @mbg.generated
     */
    public void setDecsrqInt(Integer decsrqInt) {
        this.decsrqInt = decsrqInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dexm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dexm
     *
     * @mbg.generated
     */
    public String getDexm() {
        return dexm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dexm
     *
     * @param dexm the value for ld_dwd_rk_bf_crjryjl_dd.dexm
     *
     * @mbg.generated
     */
    public void setDexm(String dexm) {
        this.dexm = dexm == null ? null : dexm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.ri
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.ri
     *
     * @mbg.generated
     */
    public String getRi() {
        return ri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.ri
     *
     * @param ri the value for ld_dwd_rk_bf_crjryjl_dd.ri
     *
     * @mbg.generated
     */
    public void setRi(String ri) {
        this.ri = ri == null ? null : ri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.xmhypy
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.xmhypy
     *
     * @mbg.generated
     */
    public String getXmhypy() {
        return xmhypy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.xmhypy
     *
     * @param xmhypy the value for ld_dwd_rk_bf_crjryjl_dd.xmhypy
     *
     * @mbg.generated
     */
    public void setXmhypy(String xmhypy) {
        this.xmhypy = xmhypy == null ? null : xmhypy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtxm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.jtxm
     *
     * @mbg.generated
     */
    public String getJtxm() {
        return jtxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.jtxm
     *
     * @param jtxm the value for ld_dwd_rk_bf_crjryjl_dd.jtxm
     *
     * @mbg.generated
     */
    public void setJtxm(String jtxm) {
        this.jtxm = jtxm == null ? null : jtxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.bmdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.bmdm
     *
     * @mbg.generated
     */
    public String getBmdm() {
        return bmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.bmdm
     *
     * @param bmdm the value for ld_dwd_rk_bf_crjryjl_dd.bmdm
     *
     * @mbg.generated
     */
    public void setBmdm(String bmdm) {
        this.bmdm = bmdm == null ? null : bmdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.bm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.bm
     *
     * @mbg.generated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.bm
     *
     * @param bm the value for ld_dwd_rk_bf_crjryjl_dd.bm
     *
     * @mbg.generated
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.wybs
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.wybs
     *
     * @mbg.generated
     */
    public String getWybs() {
        return wybs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.wybs
     *
     * @param wybs the value for ld_dwd_rk_bf_crjryjl_dd.wybs
     *
     * @mbg.generated
     */
    public void setWybs(String wybs) {
        this.wybs = wybs == null ? null : wybs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.mzdm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.mzdm
     *
     * @mbg.generated
     */
    public String getMzdm() {
        return mzdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.mzdm
     *
     * @param mzdm the value for ld_dwd_rk_bf_crjryjl_dd.mzdm
     *
     * @mbg.generated
     */
    public void setMzdm(String mzdm) {
        this.mzdm = mzdm == null ? null : mzdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.mz
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.mz
     *
     * @mbg.generated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.mz
     *
     * @param mz the value for ld_dwd_rk_bf_crjryjl_dd.mz
     *
     * @mbg.generated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.zdydm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.zdydm
     *
     * @mbg.generated
     */
    public String getZdydm() {
        return zdydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.zdydm
     *
     * @param zdydm the value for ld_dwd_rk_bf_crjryjl_dd.zdydm
     *
     * @mbg.generated
     */
    public void setZdydm(String zdydm) {
        this.zdydm = zdydm == null ? null : zdydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.zztdbj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.zztdbj
     *
     * @mbg.generated
     */
    public String getZztdbj() {
        return zztdbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.zztdbj
     *
     * @param zztdbj the value for ld_dwd_rk_bf_crjryjl_dd.zztdbj
     *
     * @mbg.generated
     */
    public void setZztdbj(String zztdbj) {
        this.zztdbj = zztdbj == null ? null : zztdbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.htblbj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.htblbj
     *
     * @mbg.generated
     */
    public String getHtblbj() {
        return htblbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.htblbj
     *
     * @param htblbj the value for ld_dwd_rk_bf_crjryjl_dd.htblbj
     *
     * @mbg.generated
     */
    public void setHtblbj(String htblbj) {
        this.htblbj = htblbj == null ? null : htblbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.crbz
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.crbz
     *
     * @mbg.generated
     */
    public String getCrbz() {
        return crbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.crbz
     *
     * @param crbz the value for ld_dwd_rk_bf_crjryjl_dd.crbz
     *
     * @mbg.generated
     */
    public void setCrbz(String crbz) {
        this.crbz = crbz == null ? null : crbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.bgczy
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.bgczy
     *
     * @mbg.generated
     */
    public String getBgczy() {
        return bgczy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.bgczy
     *
     * @param bgczy the value for ld_dwd_rk_bf_crjryjl_dd.bgczy
     *
     * @mbg.generated
     */
    public void setBgczy(String bgczy) {
        this.bgczy = bgczy == null ? null : bgczy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.bgczsj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.bgczsj
     *
     * @mbg.generated
     */
    public String getBgczsj() {
        return bgczsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.bgczsj
     *
     * @param bgczsj the value for ld_dwd_rk_bf_crjryjl_dd.bgczsj
     *
     * @mbg.generated
     */
    public void setBgczsj(String bgczsj) {
        this.bgczsj = bgczsj == null ? null : bgczsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.qzh
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.qzh
     *
     * @mbg.generated
     */
    public String getQzh() {
        return qzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.qzh
     *
     * @param qzh the value for ld_dwd_rk_bf_crjryjl_dd.qzh
     *
     * @mbg.generated
     */
    public void setQzh(String qzh) {
        this.qzh = qzh == null ? null : qzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.tlq
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.tlq
     *
     * @mbg.generated
     */
    public String getTlq() {
        return tlq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.tlq
     *
     * @param tlq the value for ld_dwd_rk_bf_crjryjl_dd.tlq
     *
     * @mbg.generated
     */
    public void setTlq(String tlq) {
        this.tlq = tlq == null ? null : tlq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.czmc
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.czmc
     *
     * @mbg.generated
     */
    public String getCzmc() {
        return czmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.czmc
     *
     * @param czmc the value for ld_dwd_rk_bf_crjryjl_dd.czmc
     *
     * @mbg.generated
     */
    public void setCzmc(String czmc) {
        this.czmc = czmc == null ? null : czmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.bf_rksj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.bf_rksj
     *
     * @mbg.generated
     */
    public String getBfRksj() {
        return bfRksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.bf_rksj
     *
     * @param bfRksj the value for ld_dwd_rk_bf_crjryjl_dd.bf_rksj
     *
     * @mbg.generated
     */
    public void setBfRksj(String bfRksj) {
        this.bfRksj = bfRksj == null ? null : bfRksj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.tb_bjzd
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.tb_bjzd
     *
     * @mbg.generated
     */
    public String getTbBjzd() {
        return tbBjzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.tb_bjzd
     *
     * @param tbBjzd the value for ld_dwd_rk_bf_crjryjl_dd.tb_bjzd
     *
     * @mbg.generated
     */
    public void setTbBjzd(String tbBjzd) {
        this.tbBjzd = tbBjzd == null ? null : tbBjzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.tb_xlbh
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.tb_xlbh
     *
     * @mbg.generated
     */
    public String getTbXlbh() {
        return tbXlbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.tb_xlbh
     *
     * @param tbXlbh the value for ld_dwd_rk_bf_crjryjl_dd.tb_xlbh
     *
     * @mbg.generated
     */
    public void setTbXlbh(String tbXlbh) {
        this.tbXlbh = tbXlbh == null ? null : tbXlbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.tb_rksj
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.tb_rksj
     *
     * @mbg.generated
     */
    public String getTbRksj() {
        return tbRksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.tb_rksj
     *
     * @param tbRksj the value for ld_dwd_rk_bf_crjryjl_dd.tb_rksj
     *
     * @mbg.generated
     */
    public void setTbRksj(String tbRksj) {
        this.tbRksj = tbRksj == null ? null : tbRksj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.op_type
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.op_type
     *
     * @mbg.generated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.op_type
     *
     * @param opType the value for ld_dwd_rk_bf_crjryjl_dd.op_type
     *
     * @mbg.generated
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.time_stamp
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.time_stamp
     *
     * @mbg.generated
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.time_stamp
     *
     * @param timeStamp the value for ld_dwd_rk_bf_crjryjl_dd.time_stamp
     *
     * @mbg.generated
     */
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp == null ? null : timeStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.gmsfhm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.gmsfhm
     *
     * @mbg.generated
     */
    public String getGmsfhm() {
        return gmsfhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.gmsfhm
     *
     * @param gmsfhm the value for ld_dwd_rk_bf_crjryjl_dd.gmsfhm
     *
     * @mbg.generated
     */
    public void setGmsfhm(String gmsfhm) {
        this.gmsfhm = gmsfhm == null ? null : gmsfhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_zjhm
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dwd_zjhm
     *
     * @mbg.generated
     */
    public String getDwdZjhm() {
        return dwdZjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_zjhm
     *
     * @param dwdZjhm the value for ld_dwd_rk_bf_crjryjl_dd.dwd_zjhm
     *
     * @mbg.generated
     */
    public void setDwdZjhm(String dwdZjhm) {
        this.dwdZjhm = dwdZjhm == null ? null : dwdZjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_loadtime
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dwd_loadtime
     *
     * @mbg.generated
     */
    public String getDwdLoadtime() {
        return dwdLoadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_loadtime
     *
     * @param dwdLoadtime the value for ld_dwd_rk_bf_crjryjl_dd.dwd_loadtime
     *
     * @mbg.generated
     */
    public void setDwdLoadtime(String dwdLoadtime) {
        this.dwdLoadtime = dwdLoadtime == null ? null : dwdLoadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_updatetime
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dwd_updatetime
     *
     * @mbg.generated
     */
    public String getDwdUpdatetime() {
        return dwdUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_updatetime
     *
     * @param dwdUpdatetime the value for ld_dwd_rk_bf_crjryjl_dd.dwd_updatetime
     *
     * @mbg.generated
     */
    public void setDwdUpdatetime(String dwdUpdatetime) {
        this.dwdUpdatetime = dwdUpdatetime == null ? null : dwdUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_yxbz
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dwd_yxbz
     *
     * @mbg.generated
     */
    public String getDwdYxbz() {
        return dwdYxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dwd_yxbz
     *
     * @param dwdYxbz the value for ld_dwd_rk_bf_crjryjl_dd.dwd_yxbz
     *
     * @mbg.generated
     */
    public void setDwdYxbz(String dwdYxbz) {
        this.dwdYxbz = dwdYxbz == null ? null : dwdYxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_dwd_rk_bf_crjryjl_dd.dep_code
     *
     * @return the value of ld_dwd_rk_bf_crjryjl_dd.dep_code
     *
     * @mbg.generated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_dwd_rk_bf_crjryjl_dd.dep_code
     *
     * @param depCode the value for ld_dwd_rk_bf_crjryjl_dd.dep_code
     *
     * @mbg.generated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_dwd_rk_bf_crjryjl_dd
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", crjrylbdm=").append(crjrylbdm);
        sb.append(", crjrylb=").append(crjrylb);
        sb.append(", xm=").append(xm);
        sb.append(", gjhdqdm=").append(gjhdqdm);
        sb.append(", gjhdq=").append(gjhdq);
        sb.append(", xbdm=").append(xbdm);
        sb.append(", xb=").append(xb);
        sb.append(", csrq=").append(csrq);
        sb.append(", csrqDt=").append(csrqDt);
        sb.append(", csrqInt=").append(csrqInt);
        sb.append(", cyzjlbdm=").append(cyzjlbdm);
        sb.append(", cyzjlb=").append(cyzjlb);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", zgqzzldm=").append(zgqzzldm);
        sb.append(", zgqzzl=").append(zgqzzl);
        sb.append(", crrq=").append(crrq);
        sb.append(", crrqDt=").append(crrqDt);
        sb.append(", crrqInt=").append(crrqInt);
        sb.append(", crsj=").append(crsj);
        sb.append(", crrqsj=").append(crrqsj);
        sb.append(", crrqsjDt=").append(crrqsjDt);
        sb.append(", crrqsjInt=").append(crrqsjInt);
        sb.append(", crkadm=").append(crkadm);
        sb.append(", crka=").append(crka);
        sb.append(", jtfsdm=").append(jtfsdm);
        sb.append(", jtfs=").append(jtfs);
        sb.append(", jtgjlb=").append(jtgjlb);
        sb.append(", qwGjhdqdm=").append(qwGjhdqdm);
        sb.append(", qwGjhdq=").append(qwGjhdq);
        sb.append(", fzddm=").append(fzddm);
        sb.append(", fzd=").append(fzd);
        sb.append(", crjsy=").append(crjsy);
        sb.append(", jcyh=").append(jcyh);
        sb.append(", tdh=").append(tdh);
        sb.append(", nbth=").append(nbth);
        sb.append(", lxth=").append(lxth);
        sb.append(", ccxmBz=").append(ccxmBz);
        sb.append(", ynzsm=").append(ynzsm);
        sb.append(", dezh=").append(dezh);
        sb.append(", dezldm=").append(dezldm);
        sb.append(", dezl=").append(dezl);
        sb.append(", decsrq=").append(decsrq);
        sb.append(", decsrqDt=").append(decsrqDt);
        sb.append(", decsrqInt=").append(decsrqInt);
        sb.append(", dexm=").append(dexm);
        sb.append(", ri=").append(ri);
        sb.append(", xmhypy=").append(xmhypy);
        sb.append(", jtxm=").append(jtxm);
        sb.append(", bmdm=").append(bmdm);
        sb.append(", bm=").append(bm);
        sb.append(", wybs=").append(wybs);
        sb.append(", mzdm=").append(mzdm);
        sb.append(", mz=").append(mz);
        sb.append(", zdydm=").append(zdydm);
        sb.append(", zztdbj=").append(zztdbj);
        sb.append(", htblbj=").append(htblbj);
        sb.append(", crbz=").append(crbz);
        sb.append(", bgczy=").append(bgczy);
        sb.append(", bgczsj=").append(bgczsj);
        sb.append(", qzh=").append(qzh);
        sb.append(", tlq=").append(tlq);
        sb.append(", czmc=").append(czmc);
        sb.append(", bfRksj=").append(bfRksj);
        sb.append(", tbBjzd=").append(tbBjzd);
        sb.append(", tbXlbh=").append(tbXlbh);
        sb.append(", tbRksj=").append(tbRksj);
        sb.append(", opType=").append(opType);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", gmsfhm=").append(gmsfhm);
        sb.append(", dwdZjhm=").append(dwdZjhm);
        sb.append(", dwdLoadtime=").append(dwdLoadtime);
        sb.append(", dwdUpdatetime=").append(dwdUpdatetime);
        sb.append(", dwdYxbz=").append(dwdYxbz);
        sb.append(", depCode=").append(depCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}